// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protocol/state.proto
// Protobuf C++ Version: 5.29.1

#ifndef protocol_2fstate_2eproto_2epb_2eh
#define protocol_2fstate_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "protocol/candidate_window.pb.h"
#include "protocol/commands.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_protocol_2fstate_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_protocol_2fstate_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_protocol_2fstate_2eproto;
namespace mozc {
namespace protocol {
class SessionState;
struct SessionStateDefaultTypeInternal;
extern SessionStateDefaultTypeInternal _SessionState_default_instance_;
}  // namespace protocol
}  // namespace mozc
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace mozc {
namespace protocol {

// ===================================================================


// -------------------------------------------------------------------

class SessionState final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:mozc.protocol.SessionState) */ {
 public:
  inline SessionState() : SessionState(nullptr) {}
  ~SessionState() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SessionState* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SessionState));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SessionState(
      ::google::protobuf::internal::ConstantInitialized);

  inline SessionState(const SessionState& from) : SessionState(nullptr, from) {}
  inline SessionState(SessionState&& from) noexcept
      : SessionState(nullptr, std::move(from)) {}
  inline SessionState& operator=(const SessionState& from) {
    CopyFrom(from);
    return *this;
  }
  inline SessionState& operator=(SessionState&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SessionState& default_instance() {
    return *internal_default_instance();
  }
  static inline const SessionState* internal_default_instance() {
    return reinterpret_cast<const SessionState*>(
        &_SessionState_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(SessionState& a, SessionState& b) { a.Swap(&b); }
  inline void Swap(SessionState* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SessionState* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SessionState* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SessionState>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SessionState& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SessionState& from) { SessionState::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SessionState* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "mozc.protocol.SessionState"; }

 protected:
  explicit SessionState(::google::protobuf::Arena* arena);
  SessionState(::google::protobuf::Arena* arena, const SessionState& from);
  SessionState(::google::protobuf::Arena* arena, SessionState&& from) noexcept
      : SessionState(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPreeditFieldNumber = 20,
    kCandidateWindowFieldNumber = 21,
    kResultFieldNumber = 23,
    kRequestFieldNumber = 24,
    kIdFieldNumber = 1,
    kCreatedTimeFieldNumber = 2,
    kStartPreeditTimeFieldNumber = 10,
    kStartConversionWindowTimeFieldNumber = 11,
    kStartPredictionWindowTimeFieldNumber = 12,
    kStartSuggestionWindowTimeFieldNumber = 13,
    kStartInfolistWindowTimeFieldNumber = 14,
    kCommittedFieldNumber = 3,
    kInputFieldTypeFieldNumber = 25,
  };
  // optional .mozc.commands.Preedit preedit = 20;
  bool has_preedit() const;
  void clear_preedit() ;
  const ::mozc::commands::Preedit& preedit() const;
  PROTOBUF_NODISCARD ::mozc::commands::Preedit* release_preedit();
  ::mozc::commands::Preedit* mutable_preedit();
  void set_allocated_preedit(::mozc::commands::Preedit* value);
  void unsafe_arena_set_allocated_preedit(::mozc::commands::Preedit* value);
  ::mozc::commands::Preedit* unsafe_arena_release_preedit();

  private:
  const ::mozc::commands::Preedit& _internal_preedit() const;
  ::mozc::commands::Preedit* _internal_mutable_preedit();

  public:
  // optional .mozc.commands.CandidateWindow candidate_window = 21;
  bool has_candidate_window() const;
  void clear_candidate_window() ;
  const ::mozc::commands::CandidateWindow& candidate_window() const;
  PROTOBUF_NODISCARD ::mozc::commands::CandidateWindow* release_candidate_window();
  ::mozc::commands::CandidateWindow* mutable_candidate_window();
  void set_allocated_candidate_window(::mozc::commands::CandidateWindow* value);
  void unsafe_arena_set_allocated_candidate_window(::mozc::commands::CandidateWindow* value);
  ::mozc::commands::CandidateWindow* unsafe_arena_release_candidate_window();

  private:
  const ::mozc::commands::CandidateWindow& _internal_candidate_window() const;
  ::mozc::commands::CandidateWindow* _internal_mutable_candidate_window();

  public:
  // optional .mozc.commands.Result result = 23;
  bool has_result() const;
  void clear_result() ;
  const ::mozc::commands::Result& result() const;
  PROTOBUF_NODISCARD ::mozc::commands::Result* release_result();
  ::mozc::commands::Result* mutable_result();
  void set_allocated_result(::mozc::commands::Result* value);
  void unsafe_arena_set_allocated_result(::mozc::commands::Result* value);
  ::mozc::commands::Result* unsafe_arena_release_result();

  private:
  const ::mozc::commands::Result& _internal_result() const;
  ::mozc::commands::Result* _internal_mutable_result();

  public:
  // optional .mozc.commands.Request request = 24;
  bool has_request() const;
  void clear_request() ;
  const ::mozc::commands::Request& request() const;
  PROTOBUF_NODISCARD ::mozc::commands::Request* release_request();
  ::mozc::commands::Request* mutable_request();
  void set_allocated_request(::mozc::commands::Request* value);
  void unsafe_arena_set_allocated_request(::mozc::commands::Request* value);
  ::mozc::commands::Request* unsafe_arena_release_request();

  private:
  const ::mozc::commands::Request& _internal_request() const;
  ::mozc::commands::Request* _internal_mutable_request();

  public:
  // required uint64 id = 1 [jstype = JS_STRING];
  bool has_id() const;
  void clear_id() ;
  ::uint64_t id() const;
  void set_id(::uint64_t value);

  private:
  ::uint64_t _internal_id() const;
  void _internal_set_id(::uint64_t value);

  public:
  // optional uint64 created_time = 2 [jstype = JS_STRING];
  bool has_created_time() const;
  void clear_created_time() ;
  ::uint64_t created_time() const;
  void set_created_time(::uint64_t value);

  private:
  ::uint64_t _internal_created_time() const;
  void _internal_set_created_time(::uint64_t value);

  public:
  // optional uint64 start_preedit_time = 10 [jstype = JS_STRING];
  bool has_start_preedit_time() const;
  void clear_start_preedit_time() ;
  ::uint64_t start_preedit_time() const;
  void set_start_preedit_time(::uint64_t value);

  private:
  ::uint64_t _internal_start_preedit_time() const;
  void _internal_set_start_preedit_time(::uint64_t value);

  public:
  // optional uint64 start_conversion_window_time = 11 [jstype = JS_STRING];
  bool has_start_conversion_window_time() const;
  void clear_start_conversion_window_time() ;
  ::uint64_t start_conversion_window_time() const;
  void set_start_conversion_window_time(::uint64_t value);

  private:
  ::uint64_t _internal_start_conversion_window_time() const;
  void _internal_set_start_conversion_window_time(::uint64_t value);

  public:
  // optional uint64 start_prediction_window_time = 12 [jstype = JS_STRING];
  bool has_start_prediction_window_time() const;
  void clear_start_prediction_window_time() ;
  ::uint64_t start_prediction_window_time() const;
  void set_start_prediction_window_time(::uint64_t value);

  private:
  ::uint64_t _internal_start_prediction_window_time() const;
  void _internal_set_start_prediction_window_time(::uint64_t value);

  public:
  // optional uint64 start_suggestion_window_time = 13 [jstype = JS_STRING];
  bool has_start_suggestion_window_time() const;
  void clear_start_suggestion_window_time() ;
  ::uint64_t start_suggestion_window_time() const;
  void set_start_suggestion_window_time(::uint64_t value);

  private:
  ::uint64_t _internal_start_suggestion_window_time() const;
  void _internal_set_start_suggestion_window_time(::uint64_t value);

  public:
  // optional uint64 start_infolist_window_time = 14 [jstype = JS_STRING];
  bool has_start_infolist_window_time() const;
  void clear_start_infolist_window_time() ;
  ::uint64_t start_infolist_window_time() const;
  void set_start_infolist_window_time(::uint64_t value);

  private:
  ::uint64_t _internal_start_infolist_window_time() const;
  void _internal_set_start_infolist_window_time(::uint64_t value);

  public:
  // optional bool committed = 3 [default = false];
  bool has_committed() const;
  void clear_committed() ;
  bool committed() const;
  void set_committed(bool value);

  private:
  bool _internal_committed() const;
  void _internal_set_committed(bool value);

  public:
  // optional .mozc.commands.Context.InputFieldType input_field_type = 25;
  bool has_input_field_type() const;
  void clear_input_field_type() ;
  ::mozc::commands::Context_InputFieldType input_field_type() const;
  void set_input_field_type(::mozc::commands::Context_InputFieldType value);

  private:
  ::mozc::commands::Context_InputFieldType _internal_input_field_type() const;
  void _internal_set_input_field_type(::mozc::commands::Context_InputFieldType value);

  public:
  // @@protoc_insertion_point(class_scope:mozc.protocol.SessionState)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      4, 13, 5,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SessionState& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::mozc::commands::Preedit* preedit_;
    ::mozc::commands::CandidateWindow* candidate_window_;
    ::mozc::commands::Result* result_;
    ::mozc::commands::Request* request_;
    ::uint64_t id_;
    ::uint64_t created_time_;
    ::uint64_t start_preedit_time_;
    ::uint64_t start_conversion_window_time_;
    ::uint64_t start_prediction_window_time_;
    ::uint64_t start_suggestion_window_time_;
    ::uint64_t start_infolist_window_time_;
    bool committed_;
    int input_field_type_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_protocol_2fstate_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// SessionState

// required uint64 id = 1 [jstype = JS_STRING];
inline bool SessionState::has_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline void SessionState::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline ::uint64_t SessionState::id() const {
  // @@protoc_insertion_point(field_get:mozc.protocol.SessionState.id)
  return _internal_id();
}
inline void SessionState::set_id(::uint64_t value) {
  _internal_set_id(value);
  _impl_._has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_set:mozc.protocol.SessionState.id)
}
inline ::uint64_t SessionState::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void SessionState::_internal_set_id(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// optional uint64 created_time = 2 [jstype = JS_STRING];
inline bool SessionState::has_created_time() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline void SessionState::clear_created_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.created_time_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline ::uint64_t SessionState::created_time() const {
  // @@protoc_insertion_point(field_get:mozc.protocol.SessionState.created_time)
  return _internal_created_time();
}
inline void SessionState::set_created_time(::uint64_t value) {
  _internal_set_created_time(value);
  _impl_._has_bits_[0] |= 0x00000020u;
  // @@protoc_insertion_point(field_set:mozc.protocol.SessionState.created_time)
}
inline ::uint64_t SessionState::_internal_created_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.created_time_;
}
inline void SessionState::_internal_set_created_time(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.created_time_ = value;
}

// optional bool committed = 3 [default = false];
inline bool SessionState::has_committed() const {
  bool value = (_impl_._has_bits_[0] & 0x00000800u) != 0;
  return value;
}
inline void SessionState::clear_committed() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.committed_ = false;
  _impl_._has_bits_[0] &= ~0x00000800u;
}
inline bool SessionState::committed() const {
  // @@protoc_insertion_point(field_get:mozc.protocol.SessionState.committed)
  return _internal_committed();
}
inline void SessionState::set_committed(bool value) {
  _internal_set_committed(value);
  _impl_._has_bits_[0] |= 0x00000800u;
  // @@protoc_insertion_point(field_set:mozc.protocol.SessionState.committed)
}
inline bool SessionState::_internal_committed() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.committed_;
}
inline void SessionState::_internal_set_committed(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.committed_ = value;
}

// optional uint64 start_preedit_time = 10 [jstype = JS_STRING];
inline bool SessionState::has_start_preedit_time() const {
  bool value = (_impl_._has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline void SessionState::clear_start_preedit_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.start_preedit_time_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline ::uint64_t SessionState::start_preedit_time() const {
  // @@protoc_insertion_point(field_get:mozc.protocol.SessionState.start_preedit_time)
  return _internal_start_preedit_time();
}
inline void SessionState::set_start_preedit_time(::uint64_t value) {
  _internal_set_start_preedit_time(value);
  _impl_._has_bits_[0] |= 0x00000040u;
  // @@protoc_insertion_point(field_set:mozc.protocol.SessionState.start_preedit_time)
}
inline ::uint64_t SessionState::_internal_start_preedit_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.start_preedit_time_;
}
inline void SessionState::_internal_set_start_preedit_time(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.start_preedit_time_ = value;
}

// optional uint64 start_conversion_window_time = 11 [jstype = JS_STRING];
inline bool SessionState::has_start_conversion_window_time() const {
  bool value = (_impl_._has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline void SessionState::clear_start_conversion_window_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.start_conversion_window_time_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000080u;
}
inline ::uint64_t SessionState::start_conversion_window_time() const {
  // @@protoc_insertion_point(field_get:mozc.protocol.SessionState.start_conversion_window_time)
  return _internal_start_conversion_window_time();
}
inline void SessionState::set_start_conversion_window_time(::uint64_t value) {
  _internal_set_start_conversion_window_time(value);
  _impl_._has_bits_[0] |= 0x00000080u;
  // @@protoc_insertion_point(field_set:mozc.protocol.SessionState.start_conversion_window_time)
}
inline ::uint64_t SessionState::_internal_start_conversion_window_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.start_conversion_window_time_;
}
inline void SessionState::_internal_set_start_conversion_window_time(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.start_conversion_window_time_ = value;
}

// optional uint64 start_prediction_window_time = 12 [jstype = JS_STRING];
inline bool SessionState::has_start_prediction_window_time() const {
  bool value = (_impl_._has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline void SessionState::clear_start_prediction_window_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.start_prediction_window_time_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000100u;
}
inline ::uint64_t SessionState::start_prediction_window_time() const {
  // @@protoc_insertion_point(field_get:mozc.protocol.SessionState.start_prediction_window_time)
  return _internal_start_prediction_window_time();
}
inline void SessionState::set_start_prediction_window_time(::uint64_t value) {
  _internal_set_start_prediction_window_time(value);
  _impl_._has_bits_[0] |= 0x00000100u;
  // @@protoc_insertion_point(field_set:mozc.protocol.SessionState.start_prediction_window_time)
}
inline ::uint64_t SessionState::_internal_start_prediction_window_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.start_prediction_window_time_;
}
inline void SessionState::_internal_set_start_prediction_window_time(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.start_prediction_window_time_ = value;
}

// optional uint64 start_suggestion_window_time = 13 [jstype = JS_STRING];
inline bool SessionState::has_start_suggestion_window_time() const {
  bool value = (_impl_._has_bits_[0] & 0x00000200u) != 0;
  return value;
}
inline void SessionState::clear_start_suggestion_window_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.start_suggestion_window_time_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000200u;
}
inline ::uint64_t SessionState::start_suggestion_window_time() const {
  // @@protoc_insertion_point(field_get:mozc.protocol.SessionState.start_suggestion_window_time)
  return _internal_start_suggestion_window_time();
}
inline void SessionState::set_start_suggestion_window_time(::uint64_t value) {
  _internal_set_start_suggestion_window_time(value);
  _impl_._has_bits_[0] |= 0x00000200u;
  // @@protoc_insertion_point(field_set:mozc.protocol.SessionState.start_suggestion_window_time)
}
inline ::uint64_t SessionState::_internal_start_suggestion_window_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.start_suggestion_window_time_;
}
inline void SessionState::_internal_set_start_suggestion_window_time(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.start_suggestion_window_time_ = value;
}

// optional uint64 start_infolist_window_time = 14 [jstype = JS_STRING];
inline bool SessionState::has_start_infolist_window_time() const {
  bool value = (_impl_._has_bits_[0] & 0x00000400u) != 0;
  return value;
}
inline void SessionState::clear_start_infolist_window_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.start_infolist_window_time_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000400u;
}
inline ::uint64_t SessionState::start_infolist_window_time() const {
  // @@protoc_insertion_point(field_get:mozc.protocol.SessionState.start_infolist_window_time)
  return _internal_start_infolist_window_time();
}
inline void SessionState::set_start_infolist_window_time(::uint64_t value) {
  _internal_set_start_infolist_window_time(value);
  _impl_._has_bits_[0] |= 0x00000400u;
  // @@protoc_insertion_point(field_set:mozc.protocol.SessionState.start_infolist_window_time)
}
inline ::uint64_t SessionState::_internal_start_infolist_window_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.start_infolist_window_time_;
}
inline void SessionState::_internal_set_start_infolist_window_time(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.start_infolist_window_time_ = value;
}

// optional .mozc.commands.Preedit preedit = 20;
inline bool SessionState::has_preedit() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.preedit_ != nullptr);
  return value;
}
inline const ::mozc::commands::Preedit& SessionState::_internal_preedit() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::mozc::commands::Preedit* p = _impl_.preedit_;
  return p != nullptr ? *p : reinterpret_cast<const ::mozc::commands::Preedit&>(::mozc::commands::_Preedit_default_instance_);
}
inline const ::mozc::commands::Preedit& SessionState::preedit() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mozc.protocol.SessionState.preedit)
  return _internal_preedit();
}
inline void SessionState::unsafe_arena_set_allocated_preedit(::mozc::commands::Preedit* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.preedit_);
  }
  _impl_.preedit_ = reinterpret_cast<::mozc::commands::Preedit*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mozc.protocol.SessionState.preedit)
}
inline ::mozc::commands::Preedit* SessionState::release_preedit() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::mozc::commands::Preedit* released = _impl_.preedit_;
  _impl_.preedit_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::mozc::commands::Preedit* SessionState::unsafe_arena_release_preedit() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mozc.protocol.SessionState.preedit)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::mozc::commands::Preedit* temp = _impl_.preedit_;
  _impl_.preedit_ = nullptr;
  return temp;
}
inline ::mozc::commands::Preedit* SessionState::_internal_mutable_preedit() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.preedit_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::mozc::commands::Preedit>(GetArena());
    _impl_.preedit_ = reinterpret_cast<::mozc::commands::Preedit*>(p);
  }
  return _impl_.preedit_;
}
inline ::mozc::commands::Preedit* SessionState::mutable_preedit() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::mozc::commands::Preedit* _msg = _internal_mutable_preedit();
  // @@protoc_insertion_point(field_mutable:mozc.protocol.SessionState.preedit)
  return _msg;
}
inline void SessionState::set_allocated_preedit(::mozc::commands::Preedit* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.preedit_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.preedit_ = reinterpret_cast<::mozc::commands::Preedit*>(value);
  // @@protoc_insertion_point(field_set_allocated:mozc.protocol.SessionState.preedit)
}

// optional .mozc.commands.CandidateWindow candidate_window = 21;
inline bool SessionState::has_candidate_window() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.candidate_window_ != nullptr);
  return value;
}
inline const ::mozc::commands::CandidateWindow& SessionState::_internal_candidate_window() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::mozc::commands::CandidateWindow* p = _impl_.candidate_window_;
  return p != nullptr ? *p : reinterpret_cast<const ::mozc::commands::CandidateWindow&>(::mozc::commands::_CandidateWindow_default_instance_);
}
inline const ::mozc::commands::CandidateWindow& SessionState::candidate_window() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mozc.protocol.SessionState.candidate_window)
  return _internal_candidate_window();
}
inline void SessionState::unsafe_arena_set_allocated_candidate_window(::mozc::commands::CandidateWindow* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.candidate_window_);
  }
  _impl_.candidate_window_ = reinterpret_cast<::mozc::commands::CandidateWindow*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mozc.protocol.SessionState.candidate_window)
}
inline ::mozc::commands::CandidateWindow* SessionState::release_candidate_window() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::mozc::commands::CandidateWindow* released = _impl_.candidate_window_;
  _impl_.candidate_window_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::mozc::commands::CandidateWindow* SessionState::unsafe_arena_release_candidate_window() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mozc.protocol.SessionState.candidate_window)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::mozc::commands::CandidateWindow* temp = _impl_.candidate_window_;
  _impl_.candidate_window_ = nullptr;
  return temp;
}
inline ::mozc::commands::CandidateWindow* SessionState::_internal_mutable_candidate_window() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.candidate_window_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::mozc::commands::CandidateWindow>(GetArena());
    _impl_.candidate_window_ = reinterpret_cast<::mozc::commands::CandidateWindow*>(p);
  }
  return _impl_.candidate_window_;
}
inline ::mozc::commands::CandidateWindow* SessionState::mutable_candidate_window() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::mozc::commands::CandidateWindow* _msg = _internal_mutable_candidate_window();
  // @@protoc_insertion_point(field_mutable:mozc.protocol.SessionState.candidate_window)
  return _msg;
}
inline void SessionState::set_allocated_candidate_window(::mozc::commands::CandidateWindow* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.candidate_window_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.candidate_window_ = reinterpret_cast<::mozc::commands::CandidateWindow*>(value);
  // @@protoc_insertion_point(field_set_allocated:mozc.protocol.SessionState.candidate_window)
}

// optional .mozc.commands.Result result = 23;
inline bool SessionState::has_result() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.result_ != nullptr);
  return value;
}
inline const ::mozc::commands::Result& SessionState::_internal_result() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::mozc::commands::Result* p = _impl_.result_;
  return p != nullptr ? *p : reinterpret_cast<const ::mozc::commands::Result&>(::mozc::commands::_Result_default_instance_);
}
inline const ::mozc::commands::Result& SessionState::result() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mozc.protocol.SessionState.result)
  return _internal_result();
}
inline void SessionState::unsafe_arena_set_allocated_result(::mozc::commands::Result* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.result_);
  }
  _impl_.result_ = reinterpret_cast<::mozc::commands::Result*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mozc.protocol.SessionState.result)
}
inline ::mozc::commands::Result* SessionState::release_result() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::mozc::commands::Result* released = _impl_.result_;
  _impl_.result_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::mozc::commands::Result* SessionState::unsafe_arena_release_result() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mozc.protocol.SessionState.result)

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::mozc::commands::Result* temp = _impl_.result_;
  _impl_.result_ = nullptr;
  return temp;
}
inline ::mozc::commands::Result* SessionState::_internal_mutable_result() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.result_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::mozc::commands::Result>(GetArena());
    _impl_.result_ = reinterpret_cast<::mozc::commands::Result*>(p);
  }
  return _impl_.result_;
}
inline ::mozc::commands::Result* SessionState::mutable_result() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000004u;
  ::mozc::commands::Result* _msg = _internal_mutable_result();
  // @@protoc_insertion_point(field_mutable:mozc.protocol.SessionState.result)
  return _msg;
}
inline void SessionState::set_allocated_result(::mozc::commands::Result* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.result_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }

  _impl_.result_ = reinterpret_cast<::mozc::commands::Result*>(value);
  // @@protoc_insertion_point(field_set_allocated:mozc.protocol.SessionState.result)
}

// optional .mozc.commands.Request request = 24;
inline bool SessionState::has_request() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.request_ != nullptr);
  return value;
}
inline const ::mozc::commands::Request& SessionState::_internal_request() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::mozc::commands::Request* p = _impl_.request_;
  return p != nullptr ? *p : reinterpret_cast<const ::mozc::commands::Request&>(::mozc::commands::_Request_default_instance_);
}
inline const ::mozc::commands::Request& SessionState::request() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mozc.protocol.SessionState.request)
  return _internal_request();
}
inline void SessionState::unsafe_arena_set_allocated_request(::mozc::commands::Request* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.request_);
  }
  _impl_.request_ = reinterpret_cast<::mozc::commands::Request*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mozc.protocol.SessionState.request)
}
inline ::mozc::commands::Request* SessionState::release_request() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000008u;
  ::mozc::commands::Request* released = _impl_.request_;
  _impl_.request_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::mozc::commands::Request* SessionState::unsafe_arena_release_request() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mozc.protocol.SessionState.request)

  _impl_._has_bits_[0] &= ~0x00000008u;
  ::mozc::commands::Request* temp = _impl_.request_;
  _impl_.request_ = nullptr;
  return temp;
}
inline ::mozc::commands::Request* SessionState::_internal_mutable_request() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.request_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::mozc::commands::Request>(GetArena());
    _impl_.request_ = reinterpret_cast<::mozc::commands::Request*>(p);
  }
  return _impl_.request_;
}
inline ::mozc::commands::Request* SessionState::mutable_request() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000008u;
  ::mozc::commands::Request* _msg = _internal_mutable_request();
  // @@protoc_insertion_point(field_mutable:mozc.protocol.SessionState.request)
  return _msg;
}
inline void SessionState::set_allocated_request(::mozc::commands::Request* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.request_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }

  _impl_.request_ = reinterpret_cast<::mozc::commands::Request*>(value);
  // @@protoc_insertion_point(field_set_allocated:mozc.protocol.SessionState.request)
}

// optional .mozc.commands.Context.InputFieldType input_field_type = 25;
inline bool SessionState::has_input_field_type() const {
  bool value = (_impl_._has_bits_[0] & 0x00001000u) != 0;
  return value;
}
inline void SessionState::clear_input_field_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.input_field_type_ = 1;
  _impl_._has_bits_[0] &= ~0x00001000u;
}
inline ::mozc::commands::Context_InputFieldType SessionState::input_field_type() const {
  // @@protoc_insertion_point(field_get:mozc.protocol.SessionState.input_field_type)
  return _internal_input_field_type();
}
inline void SessionState::set_input_field_type(::mozc::commands::Context_InputFieldType value) {
  _internal_set_input_field_type(value);
  _impl_._has_bits_[0] |= 0x00001000u;
  // @@protoc_insertion_point(field_set:mozc.protocol.SessionState.input_field_type)
}
inline ::mozc::commands::Context_InputFieldType SessionState::_internal_input_field_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::mozc::commands::Context_InputFieldType>(_impl_.input_field_type_);
}
inline void SessionState::_internal_set_input_field_type(::mozc::commands::Context_InputFieldType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  assert(::mozc::commands::Context_InputFieldType_IsValid(value));
  _impl_.input_field_type_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace protocol
}  // namespace mozc


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // protocol_2fstate_2eproto_2epb_2eh
