// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: usage_stats/usage_stats.proto
// Protobuf C++ Version: 5.29.1

#ifndef usage_5fstats_2fusage_5fstats_2eproto_2epb_2eh
#define usage_5fstats_2fusage_5fstats_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_usage_5fstats_2fusage_5fstats_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_usage_5fstats_2fusage_5fstats_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_usage_5fstats_2fusage_5fstats_2eproto;
namespace mozc {
namespace usage_stats {
class Stats;
struct StatsDefaultTypeInternal;
extern StatsDefaultTypeInternal _Stats_default_instance_;
class Stats_DoubleValueStats;
struct Stats_DoubleValueStatsDefaultTypeInternal;
extern Stats_DoubleValueStatsDefaultTypeInternal _Stats_DoubleValueStats_default_instance_;
class Stats_TouchEventStats;
struct Stats_TouchEventStatsDefaultTypeInternal;
extern Stats_TouchEventStatsDefaultTypeInternal _Stats_TouchEventStats_default_instance_;
class Stats_VirtualKeyboardStats;
struct Stats_VirtualKeyboardStatsDefaultTypeInternal;
extern Stats_VirtualKeyboardStatsDefaultTypeInternal _Stats_VirtualKeyboardStats_default_instance_;
}  // namespace usage_stats
}  // namespace mozc
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace mozc {
namespace usage_stats {
enum Stats_Type : int {
  Stats_Type_COUNT = 0,
  Stats_Type_TIMING = 1,
  Stats_Type_INTEGER = 2,
  Stats_Type_BOOLEAN = 3,
  Stats_Type_VIRTUAL_KEYBOARD = 4,
};

bool Stats_Type_IsValid(int value);
extern const uint32_t Stats_Type_internal_data_[];
constexpr Stats_Type Stats_Type_Type_MIN = static_cast<Stats_Type>(0);
constexpr Stats_Type Stats_Type_Type_MAX = static_cast<Stats_Type>(4);
constexpr int Stats_Type_Type_ARRAYSIZE = 4 + 1;
const ::google::protobuf::EnumDescriptor*
Stats_Type_descriptor();
template <typename T>
const std::string& Stats_Type_Name(T value) {
  static_assert(std::is_same<T, Stats_Type>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to Type_Name().");
  return Stats_Type_Name(static_cast<Stats_Type>(value));
}
template <>
inline const std::string& Stats_Type_Name(Stats_Type value) {
  return ::google::protobuf::internal::NameOfDenseEnum<Stats_Type_descriptor,
                                                 0, 4>(
      static_cast<int>(value));
}
inline bool Stats_Type_Parse(absl::string_view name, Stats_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Stats_Type>(
      Stats_Type_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class Stats_DoubleValueStats final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:mozc.usage_stats.Stats.DoubleValueStats) */ {
 public:
  inline Stats_DoubleValueStats() : Stats_DoubleValueStats(nullptr) {}
  ~Stats_DoubleValueStats() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Stats_DoubleValueStats* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Stats_DoubleValueStats));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Stats_DoubleValueStats(
      ::google::protobuf::internal::ConstantInitialized);

  inline Stats_DoubleValueStats(const Stats_DoubleValueStats& from) : Stats_DoubleValueStats(nullptr, from) {}
  inline Stats_DoubleValueStats(Stats_DoubleValueStats&& from) noexcept
      : Stats_DoubleValueStats(nullptr, std::move(from)) {}
  inline Stats_DoubleValueStats& operator=(const Stats_DoubleValueStats& from) {
    CopyFrom(from);
    return *this;
  }
  inline Stats_DoubleValueStats& operator=(Stats_DoubleValueStats&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Stats_DoubleValueStats& default_instance() {
    return *internal_default_instance();
  }
  static inline const Stats_DoubleValueStats* internal_default_instance() {
    return reinterpret_cast<const Stats_DoubleValueStats*>(
        &_Stats_DoubleValueStats_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Stats_DoubleValueStats& a, Stats_DoubleValueStats& b) { a.Swap(&b); }
  inline void Swap(Stats_DoubleValueStats* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Stats_DoubleValueStats* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Stats_DoubleValueStats* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Stats_DoubleValueStats>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Stats_DoubleValueStats& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Stats_DoubleValueStats& from) { Stats_DoubleValueStats::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Stats_DoubleValueStats* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "mozc.usage_stats.Stats.DoubleValueStats"; }

 protected:
  explicit Stats_DoubleValueStats(::google::protobuf::Arena* arena);
  Stats_DoubleValueStats(::google::protobuf::Arena* arena, const Stats_DoubleValueStats& from);
  Stats_DoubleValueStats(::google::protobuf::Arena* arena, Stats_DoubleValueStats&& from) noexcept
      : Stats_DoubleValueStats(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTotalFieldNumber = 2,
    kSquareTotalFieldNumber = 3,
    kNumFieldNumber = 1,
  };
  // optional double total = 2;
  bool has_total() const;
  void clear_total() ;
  double total() const;
  void set_total(double value);

  private:
  double _internal_total() const;
  void _internal_set_total(double value);

  public:
  // optional double square_total = 3;
  bool has_square_total() const;
  void clear_square_total() ;
  double square_total() const;
  void set_square_total(double value);

  private:
  double _internal_square_total() const;
  void _internal_set_square_total(double value);

  public:
  // optional uint32 num = 1;
  bool has_num() const;
  void clear_num() ;
  ::uint32_t num() const;
  void set_num(::uint32_t value);

  private:
  ::uint32_t _internal_num() const;
  void _internal_set_num(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:mozc.usage_stats.Stats.DoubleValueStats)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Stats_DoubleValueStats& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    double total_;
    double square_total_;
    ::uint32_t num_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_usage_5fstats_2fusage_5fstats_2eproto;
};
// -------------------------------------------------------------------

class Stats_TouchEventStats final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:mozc.usage_stats.Stats.TouchEventStats) */ {
 public:
  inline Stats_TouchEventStats() : Stats_TouchEventStats(nullptr) {}
  ~Stats_TouchEventStats() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Stats_TouchEventStats* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Stats_TouchEventStats));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Stats_TouchEventStats(
      ::google::protobuf::internal::ConstantInitialized);

  inline Stats_TouchEventStats(const Stats_TouchEventStats& from) : Stats_TouchEventStats(nullptr, from) {}
  inline Stats_TouchEventStats(Stats_TouchEventStats&& from) noexcept
      : Stats_TouchEventStats(nullptr, std::move(from)) {}
  inline Stats_TouchEventStats& operator=(const Stats_TouchEventStats& from) {
    CopyFrom(from);
    return *this;
  }
  inline Stats_TouchEventStats& operator=(Stats_TouchEventStats&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Stats_TouchEventStats& default_instance() {
    return *internal_default_instance();
  }
  static inline const Stats_TouchEventStats* internal_default_instance() {
    return reinterpret_cast<const Stats_TouchEventStats*>(
        &_Stats_TouchEventStats_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(Stats_TouchEventStats& a, Stats_TouchEventStats& b) { a.Swap(&b); }
  inline void Swap(Stats_TouchEventStats* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Stats_TouchEventStats* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Stats_TouchEventStats* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Stats_TouchEventStats>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Stats_TouchEventStats& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Stats_TouchEventStats& from) { Stats_TouchEventStats::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Stats_TouchEventStats* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "mozc.usage_stats.Stats.TouchEventStats"; }

 protected:
  explicit Stats_TouchEventStats(::google::protobuf::Arena* arena);
  Stats_TouchEventStats(::google::protobuf::Arena* arena, const Stats_TouchEventStats& from);
  Stats_TouchEventStats(::google::protobuf::Arena* arena, Stats_TouchEventStats&& from) noexcept
      : Stats_TouchEventStats(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStartXStatsFieldNumber = 2,
    kStartYStatsFieldNumber = 3,
    kDirectionXStatsFieldNumber = 4,
    kDirectionYStatsFieldNumber = 5,
    kTimeLengthStatsFieldNumber = 6,
    kSourceIdFieldNumber = 1,
  };
  // optional .mozc.usage_stats.Stats.DoubleValueStats start_x_stats = 2;
  bool has_start_x_stats() const;
  void clear_start_x_stats() ;
  const ::mozc::usage_stats::Stats_DoubleValueStats& start_x_stats() const;
  PROTOBUF_NODISCARD ::mozc::usage_stats::Stats_DoubleValueStats* release_start_x_stats();
  ::mozc::usage_stats::Stats_DoubleValueStats* mutable_start_x_stats();
  void set_allocated_start_x_stats(::mozc::usage_stats::Stats_DoubleValueStats* value);
  void unsafe_arena_set_allocated_start_x_stats(::mozc::usage_stats::Stats_DoubleValueStats* value);
  ::mozc::usage_stats::Stats_DoubleValueStats* unsafe_arena_release_start_x_stats();

  private:
  const ::mozc::usage_stats::Stats_DoubleValueStats& _internal_start_x_stats() const;
  ::mozc::usage_stats::Stats_DoubleValueStats* _internal_mutable_start_x_stats();

  public:
  // optional .mozc.usage_stats.Stats.DoubleValueStats start_y_stats = 3;
  bool has_start_y_stats() const;
  void clear_start_y_stats() ;
  const ::mozc::usage_stats::Stats_DoubleValueStats& start_y_stats() const;
  PROTOBUF_NODISCARD ::mozc::usage_stats::Stats_DoubleValueStats* release_start_y_stats();
  ::mozc::usage_stats::Stats_DoubleValueStats* mutable_start_y_stats();
  void set_allocated_start_y_stats(::mozc::usage_stats::Stats_DoubleValueStats* value);
  void unsafe_arena_set_allocated_start_y_stats(::mozc::usage_stats::Stats_DoubleValueStats* value);
  ::mozc::usage_stats::Stats_DoubleValueStats* unsafe_arena_release_start_y_stats();

  private:
  const ::mozc::usage_stats::Stats_DoubleValueStats& _internal_start_y_stats() const;
  ::mozc::usage_stats::Stats_DoubleValueStats* _internal_mutable_start_y_stats();

  public:
  // optional .mozc.usage_stats.Stats.DoubleValueStats direction_x_stats = 4;
  bool has_direction_x_stats() const;
  void clear_direction_x_stats() ;
  const ::mozc::usage_stats::Stats_DoubleValueStats& direction_x_stats() const;
  PROTOBUF_NODISCARD ::mozc::usage_stats::Stats_DoubleValueStats* release_direction_x_stats();
  ::mozc::usage_stats::Stats_DoubleValueStats* mutable_direction_x_stats();
  void set_allocated_direction_x_stats(::mozc::usage_stats::Stats_DoubleValueStats* value);
  void unsafe_arena_set_allocated_direction_x_stats(::mozc::usage_stats::Stats_DoubleValueStats* value);
  ::mozc::usage_stats::Stats_DoubleValueStats* unsafe_arena_release_direction_x_stats();

  private:
  const ::mozc::usage_stats::Stats_DoubleValueStats& _internal_direction_x_stats() const;
  ::mozc::usage_stats::Stats_DoubleValueStats* _internal_mutable_direction_x_stats();

  public:
  // optional .mozc.usage_stats.Stats.DoubleValueStats direction_y_stats = 5;
  bool has_direction_y_stats() const;
  void clear_direction_y_stats() ;
  const ::mozc::usage_stats::Stats_DoubleValueStats& direction_y_stats() const;
  PROTOBUF_NODISCARD ::mozc::usage_stats::Stats_DoubleValueStats* release_direction_y_stats();
  ::mozc::usage_stats::Stats_DoubleValueStats* mutable_direction_y_stats();
  void set_allocated_direction_y_stats(::mozc::usage_stats::Stats_DoubleValueStats* value);
  void unsafe_arena_set_allocated_direction_y_stats(::mozc::usage_stats::Stats_DoubleValueStats* value);
  ::mozc::usage_stats::Stats_DoubleValueStats* unsafe_arena_release_direction_y_stats();

  private:
  const ::mozc::usage_stats::Stats_DoubleValueStats& _internal_direction_y_stats() const;
  ::mozc::usage_stats::Stats_DoubleValueStats* _internal_mutable_direction_y_stats();

  public:
  // optional .mozc.usage_stats.Stats.DoubleValueStats time_length_stats = 6;
  bool has_time_length_stats() const;
  void clear_time_length_stats() ;
  const ::mozc::usage_stats::Stats_DoubleValueStats& time_length_stats() const;
  PROTOBUF_NODISCARD ::mozc::usage_stats::Stats_DoubleValueStats* release_time_length_stats();
  ::mozc::usage_stats::Stats_DoubleValueStats* mutable_time_length_stats();
  void set_allocated_time_length_stats(::mozc::usage_stats::Stats_DoubleValueStats* value);
  void unsafe_arena_set_allocated_time_length_stats(::mozc::usage_stats::Stats_DoubleValueStats* value);
  ::mozc::usage_stats::Stats_DoubleValueStats* unsafe_arena_release_time_length_stats();

  private:
  const ::mozc::usage_stats::Stats_DoubleValueStats& _internal_time_length_stats() const;
  ::mozc::usage_stats::Stats_DoubleValueStats* _internal_mutable_time_length_stats();

  public:
  // optional uint32 source_id = 1;
  bool has_source_id() const;
  void clear_source_id() ;
  ::uint32_t source_id() const;
  void set_source_id(::uint32_t value);

  private:
  ::uint32_t _internal_source_id() const;
  void _internal_set_source_id(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:mozc.usage_stats.Stats.TouchEventStats)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 6, 5,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Stats_TouchEventStats& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::mozc::usage_stats::Stats_DoubleValueStats* start_x_stats_;
    ::mozc::usage_stats::Stats_DoubleValueStats* start_y_stats_;
    ::mozc::usage_stats::Stats_DoubleValueStats* direction_x_stats_;
    ::mozc::usage_stats::Stats_DoubleValueStats* direction_y_stats_;
    ::mozc::usage_stats::Stats_DoubleValueStats* time_length_stats_;
    ::uint32_t source_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_usage_5fstats_2fusage_5fstats_2eproto;
};
// -------------------------------------------------------------------

class Stats_VirtualKeyboardStats final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:mozc.usage_stats.Stats.VirtualKeyboardStats) */ {
 public:
  inline Stats_VirtualKeyboardStats() : Stats_VirtualKeyboardStats(nullptr) {}
  ~Stats_VirtualKeyboardStats() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Stats_VirtualKeyboardStats* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Stats_VirtualKeyboardStats));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Stats_VirtualKeyboardStats(
      ::google::protobuf::internal::ConstantInitialized);

  inline Stats_VirtualKeyboardStats(const Stats_VirtualKeyboardStats& from) : Stats_VirtualKeyboardStats(nullptr, from) {}
  inline Stats_VirtualKeyboardStats(Stats_VirtualKeyboardStats&& from) noexcept
      : Stats_VirtualKeyboardStats(nullptr, std::move(from)) {}
  inline Stats_VirtualKeyboardStats& operator=(const Stats_VirtualKeyboardStats& from) {
    CopyFrom(from);
    return *this;
  }
  inline Stats_VirtualKeyboardStats& operator=(Stats_VirtualKeyboardStats&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Stats_VirtualKeyboardStats& default_instance() {
    return *internal_default_instance();
  }
  static inline const Stats_VirtualKeyboardStats* internal_default_instance() {
    return reinterpret_cast<const Stats_VirtualKeyboardStats*>(
        &_Stats_VirtualKeyboardStats_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(Stats_VirtualKeyboardStats& a, Stats_VirtualKeyboardStats& b) { a.Swap(&b); }
  inline void Swap(Stats_VirtualKeyboardStats* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Stats_VirtualKeyboardStats* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Stats_VirtualKeyboardStats* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Stats_VirtualKeyboardStats>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Stats_VirtualKeyboardStats& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Stats_VirtualKeyboardStats& from) { Stats_VirtualKeyboardStats::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Stats_VirtualKeyboardStats* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "mozc.usage_stats.Stats.VirtualKeyboardStats"; }

 protected:
  explicit Stats_VirtualKeyboardStats(::google::protobuf::Arena* arena);
  Stats_VirtualKeyboardStats(::google::protobuf::Arena* arena, const Stats_VirtualKeyboardStats& from);
  Stats_VirtualKeyboardStats(::google::protobuf::Arena* arena, Stats_VirtualKeyboardStats&& from) noexcept
      : Stats_VirtualKeyboardStats(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTouchEventStatsFieldNumber = 2,
    kKeyboardNameFieldNumber = 1,
  };
  // repeated .mozc.usage_stats.Stats.TouchEventStats touch_event_stats = 2;
  int touch_event_stats_size() const;
  private:
  int _internal_touch_event_stats_size() const;

  public:
  void clear_touch_event_stats() ;
  ::mozc::usage_stats::Stats_TouchEventStats* mutable_touch_event_stats(int index);
  ::google::protobuf::RepeatedPtrField<::mozc::usage_stats::Stats_TouchEventStats>* mutable_touch_event_stats();

  private:
  const ::google::protobuf::RepeatedPtrField<::mozc::usage_stats::Stats_TouchEventStats>& _internal_touch_event_stats() const;
  ::google::protobuf::RepeatedPtrField<::mozc::usage_stats::Stats_TouchEventStats>* _internal_mutable_touch_event_stats();
  public:
  const ::mozc::usage_stats::Stats_TouchEventStats& touch_event_stats(int index) const;
  ::mozc::usage_stats::Stats_TouchEventStats* add_touch_event_stats();
  const ::google::protobuf::RepeatedPtrField<::mozc::usage_stats::Stats_TouchEventStats>& touch_event_stats() const;
  // optional string keyboard_name = 1;
  bool has_keyboard_name() const;
  void clear_keyboard_name() ;
  const std::string& keyboard_name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_keyboard_name(Arg_&& arg, Args_... args);
  std::string* mutable_keyboard_name();
  PROTOBUF_NODISCARD std::string* release_keyboard_name();
  void set_allocated_keyboard_name(std::string* value);

  private:
  const std::string& _internal_keyboard_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_keyboard_name(
      const std::string& value);
  std::string* _internal_mutable_keyboard_name();

  public:
  // @@protoc_insertion_point(class_scope:mozc.usage_stats.Stats.VirtualKeyboardStats)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      65, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Stats_VirtualKeyboardStats& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::mozc::usage_stats::Stats_TouchEventStats > touch_event_stats_;
    ::google::protobuf::internal::ArenaStringPtr keyboard_name_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_usage_5fstats_2fusage_5fstats_2eproto;
};
// -------------------------------------------------------------------

class Stats final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:mozc.usage_stats.Stats) */ {
 public:
  inline Stats() : Stats(nullptr) {}
  ~Stats() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Stats* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Stats));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Stats(
      ::google::protobuf::internal::ConstantInitialized);

  inline Stats(const Stats& from) : Stats(nullptr, from) {}
  inline Stats(Stats&& from) noexcept
      : Stats(nullptr, std::move(from)) {}
  inline Stats& operator=(const Stats& from) {
    CopyFrom(from);
    return *this;
  }
  inline Stats& operator=(Stats&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Stats& default_instance() {
    return *internal_default_instance();
  }
  static inline const Stats* internal_default_instance() {
    return reinterpret_cast<const Stats*>(
        &_Stats_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(Stats& a, Stats& b) { a.Swap(&b); }
  inline void Swap(Stats* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Stats* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Stats* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Stats>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Stats& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Stats& from) { Stats::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Stats* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "mozc.usage_stats.Stats"; }

 protected:
  explicit Stats(::google::protobuf::Arena* arena);
  Stats(::google::protobuf::Arena* arena, const Stats& from);
  Stats(::google::protobuf::Arena* arena, Stats&& from) noexcept
      : Stats(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using DoubleValueStats = Stats_DoubleValueStats;
  using TouchEventStats = Stats_TouchEventStats;
  using VirtualKeyboardStats = Stats_VirtualKeyboardStats;
  using Type = Stats_Type;
  static constexpr Type COUNT = Stats_Type_COUNT;
  static constexpr Type TIMING = Stats_Type_TIMING;
  static constexpr Type INTEGER = Stats_Type_INTEGER;
  static constexpr Type BOOLEAN = Stats_Type_BOOLEAN;
  static constexpr Type VIRTUAL_KEYBOARD = Stats_Type_VIRTUAL_KEYBOARD;
  static inline bool Type_IsValid(int value) {
    return Stats_Type_IsValid(value);
  }
  static constexpr Type Type_MIN = Stats_Type_Type_MIN;
  static constexpr Type Type_MAX = Stats_Type_Type_MAX;
  static constexpr int Type_ARRAYSIZE = Stats_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* Type_descriptor() {
    return Stats_Type_descriptor();
  }
  template <typename T>
  static inline const std::string& Type_Name(T value) {
    return Stats_Type_Name(value);
  }
  static inline bool Type_Parse(absl::string_view name, Type* value) {
    return Stats_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kVirtualKeyboardStatsFieldNumber = 11,
    kNameFieldNumber = 1,
    kTypeFieldNumber = 2,
    kCountFieldNumber = 3,
    kNumTimingsFieldNumber = 4,
    kAvgTimeFieldNumber = 5,
    kMinTimeFieldNumber = 6,
    kMaxTimeFieldNumber = 7,
    kIntValueFieldNumber = 8,
    kBooleanValueFieldNumber = 9,
    kTotalTimeFieldNumber = 10,
  };
  // repeated .mozc.usage_stats.Stats.VirtualKeyboardStats virtual_keyboard_stats = 11;
  int virtual_keyboard_stats_size() const;
  private:
  int _internal_virtual_keyboard_stats_size() const;

  public:
  void clear_virtual_keyboard_stats() ;
  ::mozc::usage_stats::Stats_VirtualKeyboardStats* mutable_virtual_keyboard_stats(int index);
  ::google::protobuf::RepeatedPtrField<::mozc::usage_stats::Stats_VirtualKeyboardStats>* mutable_virtual_keyboard_stats();

  private:
  const ::google::protobuf::RepeatedPtrField<::mozc::usage_stats::Stats_VirtualKeyboardStats>& _internal_virtual_keyboard_stats() const;
  ::google::protobuf::RepeatedPtrField<::mozc::usage_stats::Stats_VirtualKeyboardStats>* _internal_mutable_virtual_keyboard_stats();
  public:
  const ::mozc::usage_stats::Stats_VirtualKeyboardStats& virtual_keyboard_stats(int index) const;
  ::mozc::usage_stats::Stats_VirtualKeyboardStats* add_virtual_keyboard_stats();
  const ::google::protobuf::RepeatedPtrField<::mozc::usage_stats::Stats_VirtualKeyboardStats>& virtual_keyboard_stats() const;
  // required string name = 1;
  bool has_name() const;
  void clear_name() ;
  const std::string& name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* value);

  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(
      const std::string& value);
  std::string* _internal_mutable_name();

  public:
  // required .mozc.usage_stats.Stats.Type type = 2;
  bool has_type() const;
  void clear_type() ;
  ::mozc::usage_stats::Stats_Type type() const;
  void set_type(::mozc::usage_stats::Stats_Type value);

  private:
  ::mozc::usage_stats::Stats_Type _internal_type() const;
  void _internal_set_type(::mozc::usage_stats::Stats_Type value);

  public:
  // optional uint32 count = 3;
  bool has_count() const;
  void clear_count() ;
  ::uint32_t count() const;
  void set_count(::uint32_t value);

  private:
  ::uint32_t _internal_count() const;
  void _internal_set_count(::uint32_t value);

  public:
  // optional uint32 num_timings = 4;
  bool has_num_timings() const;
  void clear_num_timings() ;
  ::uint32_t num_timings() const;
  void set_num_timings(::uint32_t value);

  private:
  ::uint32_t _internal_num_timings() const;
  void _internal_set_num_timings(::uint32_t value);

  public:
  // optional uint32 avg_time = 5;
  bool has_avg_time() const;
  void clear_avg_time() ;
  ::uint32_t avg_time() const;
  void set_avg_time(::uint32_t value);

  private:
  ::uint32_t _internal_avg_time() const;
  void _internal_set_avg_time(::uint32_t value);

  public:
  // optional uint32 min_time = 6;
  bool has_min_time() const;
  void clear_min_time() ;
  ::uint32_t min_time() const;
  void set_min_time(::uint32_t value);

  private:
  ::uint32_t _internal_min_time() const;
  void _internal_set_min_time(::uint32_t value);

  public:
  // optional uint32 max_time = 7;
  bool has_max_time() const;
  void clear_max_time() ;
  ::uint32_t max_time() const;
  void set_max_time(::uint32_t value);

  private:
  ::uint32_t _internal_max_time() const;
  void _internal_set_max_time(::uint32_t value);

  public:
  // optional int32 int_value = 8;
  bool has_int_value() const;
  void clear_int_value() ;
  ::int32_t int_value() const;
  void set_int_value(::int32_t value);

  private:
  ::int32_t _internal_int_value() const;
  void _internal_set_int_value(::int32_t value);

  public:
  // optional bool boolean_value = 9;
  bool has_boolean_value() const;
  void clear_boolean_value() ;
  bool boolean_value() const;
  void set_boolean_value(bool value);

  private:
  bool _internal_boolean_value() const;
  void _internal_set_boolean_value(bool value);

  public:
  // optional uint64 total_time = 10;
  bool has_total_time() const;
  void clear_total_time() ;
  ::uint64_t total_time() const;
  void set_total_time(::uint64_t value);

  private:
  ::uint64_t _internal_total_time() const;
  void _internal_set_total_time(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:mozc.usage_stats.Stats)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      4, 11, 2,
      43, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Stats& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::mozc::usage_stats::Stats_VirtualKeyboardStats > virtual_keyboard_stats_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    int type_;
    ::uint32_t count_;
    ::uint32_t num_timings_;
    ::uint32_t avg_time_;
    ::uint32_t min_time_;
    ::uint32_t max_time_;
    ::int32_t int_value_;
    bool boolean_value_;
    ::uint64_t total_time_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_usage_5fstats_2fusage_5fstats_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Stats_DoubleValueStats

// optional uint32 num = 1;
inline bool Stats_DoubleValueStats::has_num() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void Stats_DoubleValueStats::clear_num() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::uint32_t Stats_DoubleValueStats::num() const {
  // @@protoc_insertion_point(field_get:mozc.usage_stats.Stats.DoubleValueStats.num)
  return _internal_num();
}
inline void Stats_DoubleValueStats::set_num(::uint32_t value) {
  _internal_set_num(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:mozc.usage_stats.Stats.DoubleValueStats.num)
}
inline ::uint32_t Stats_DoubleValueStats::_internal_num() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.num_;
}
inline void Stats_DoubleValueStats::_internal_set_num(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num_ = value;
}

// optional double total = 2;
inline bool Stats_DoubleValueStats::has_total() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void Stats_DoubleValueStats::clear_total() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.total_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline double Stats_DoubleValueStats::total() const {
  // @@protoc_insertion_point(field_get:mozc.usage_stats.Stats.DoubleValueStats.total)
  return _internal_total();
}
inline void Stats_DoubleValueStats::set_total(double value) {
  _internal_set_total(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:mozc.usage_stats.Stats.DoubleValueStats.total)
}
inline double Stats_DoubleValueStats::_internal_total() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.total_;
}
inline void Stats_DoubleValueStats::_internal_set_total(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.total_ = value;
}

// optional double square_total = 3;
inline bool Stats_DoubleValueStats::has_square_total() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void Stats_DoubleValueStats::clear_square_total() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.square_total_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline double Stats_DoubleValueStats::square_total() const {
  // @@protoc_insertion_point(field_get:mozc.usage_stats.Stats.DoubleValueStats.square_total)
  return _internal_square_total();
}
inline void Stats_DoubleValueStats::set_square_total(double value) {
  _internal_set_square_total(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:mozc.usage_stats.Stats.DoubleValueStats.square_total)
}
inline double Stats_DoubleValueStats::_internal_square_total() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.square_total_;
}
inline void Stats_DoubleValueStats::_internal_set_square_total(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.square_total_ = value;
}

// -------------------------------------------------------------------

// Stats_TouchEventStats

// optional uint32 source_id = 1;
inline bool Stats_TouchEventStats::has_source_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline void Stats_TouchEventStats::clear_source_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.source_id_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline ::uint32_t Stats_TouchEventStats::source_id() const {
  // @@protoc_insertion_point(field_get:mozc.usage_stats.Stats.TouchEventStats.source_id)
  return _internal_source_id();
}
inline void Stats_TouchEventStats::set_source_id(::uint32_t value) {
  _internal_set_source_id(value);
  _impl_._has_bits_[0] |= 0x00000020u;
  // @@protoc_insertion_point(field_set:mozc.usage_stats.Stats.TouchEventStats.source_id)
}
inline ::uint32_t Stats_TouchEventStats::_internal_source_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.source_id_;
}
inline void Stats_TouchEventStats::_internal_set_source_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.source_id_ = value;
}

// optional .mozc.usage_stats.Stats.DoubleValueStats start_x_stats = 2;
inline bool Stats_TouchEventStats::has_start_x_stats() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.start_x_stats_ != nullptr);
  return value;
}
inline void Stats_TouchEventStats::clear_start_x_stats() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.start_x_stats_ != nullptr) _impl_.start_x_stats_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::mozc::usage_stats::Stats_DoubleValueStats& Stats_TouchEventStats::_internal_start_x_stats() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::mozc::usage_stats::Stats_DoubleValueStats* p = _impl_.start_x_stats_;
  return p != nullptr ? *p : reinterpret_cast<const ::mozc::usage_stats::Stats_DoubleValueStats&>(::mozc::usage_stats::_Stats_DoubleValueStats_default_instance_);
}
inline const ::mozc::usage_stats::Stats_DoubleValueStats& Stats_TouchEventStats::start_x_stats() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mozc.usage_stats.Stats.TouchEventStats.start_x_stats)
  return _internal_start_x_stats();
}
inline void Stats_TouchEventStats::unsafe_arena_set_allocated_start_x_stats(::mozc::usage_stats::Stats_DoubleValueStats* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.start_x_stats_);
  }
  _impl_.start_x_stats_ = reinterpret_cast<::mozc::usage_stats::Stats_DoubleValueStats*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mozc.usage_stats.Stats.TouchEventStats.start_x_stats)
}
inline ::mozc::usage_stats::Stats_DoubleValueStats* Stats_TouchEventStats::release_start_x_stats() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::mozc::usage_stats::Stats_DoubleValueStats* released = _impl_.start_x_stats_;
  _impl_.start_x_stats_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::mozc::usage_stats::Stats_DoubleValueStats* Stats_TouchEventStats::unsafe_arena_release_start_x_stats() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mozc.usage_stats.Stats.TouchEventStats.start_x_stats)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::mozc::usage_stats::Stats_DoubleValueStats* temp = _impl_.start_x_stats_;
  _impl_.start_x_stats_ = nullptr;
  return temp;
}
inline ::mozc::usage_stats::Stats_DoubleValueStats* Stats_TouchEventStats::_internal_mutable_start_x_stats() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.start_x_stats_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::mozc::usage_stats::Stats_DoubleValueStats>(GetArena());
    _impl_.start_x_stats_ = reinterpret_cast<::mozc::usage_stats::Stats_DoubleValueStats*>(p);
  }
  return _impl_.start_x_stats_;
}
inline ::mozc::usage_stats::Stats_DoubleValueStats* Stats_TouchEventStats::mutable_start_x_stats() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::mozc::usage_stats::Stats_DoubleValueStats* _msg = _internal_mutable_start_x_stats();
  // @@protoc_insertion_point(field_mutable:mozc.usage_stats.Stats.TouchEventStats.start_x_stats)
  return _msg;
}
inline void Stats_TouchEventStats::set_allocated_start_x_stats(::mozc::usage_stats::Stats_DoubleValueStats* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.start_x_stats_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.start_x_stats_ = reinterpret_cast<::mozc::usage_stats::Stats_DoubleValueStats*>(value);
  // @@protoc_insertion_point(field_set_allocated:mozc.usage_stats.Stats.TouchEventStats.start_x_stats)
}

// optional .mozc.usage_stats.Stats.DoubleValueStats start_y_stats = 3;
inline bool Stats_TouchEventStats::has_start_y_stats() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.start_y_stats_ != nullptr);
  return value;
}
inline void Stats_TouchEventStats::clear_start_y_stats() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.start_y_stats_ != nullptr) _impl_.start_y_stats_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::mozc::usage_stats::Stats_DoubleValueStats& Stats_TouchEventStats::_internal_start_y_stats() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::mozc::usage_stats::Stats_DoubleValueStats* p = _impl_.start_y_stats_;
  return p != nullptr ? *p : reinterpret_cast<const ::mozc::usage_stats::Stats_DoubleValueStats&>(::mozc::usage_stats::_Stats_DoubleValueStats_default_instance_);
}
inline const ::mozc::usage_stats::Stats_DoubleValueStats& Stats_TouchEventStats::start_y_stats() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mozc.usage_stats.Stats.TouchEventStats.start_y_stats)
  return _internal_start_y_stats();
}
inline void Stats_TouchEventStats::unsafe_arena_set_allocated_start_y_stats(::mozc::usage_stats::Stats_DoubleValueStats* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.start_y_stats_);
  }
  _impl_.start_y_stats_ = reinterpret_cast<::mozc::usage_stats::Stats_DoubleValueStats*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mozc.usage_stats.Stats.TouchEventStats.start_y_stats)
}
inline ::mozc::usage_stats::Stats_DoubleValueStats* Stats_TouchEventStats::release_start_y_stats() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::mozc::usage_stats::Stats_DoubleValueStats* released = _impl_.start_y_stats_;
  _impl_.start_y_stats_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::mozc::usage_stats::Stats_DoubleValueStats* Stats_TouchEventStats::unsafe_arena_release_start_y_stats() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mozc.usage_stats.Stats.TouchEventStats.start_y_stats)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::mozc::usage_stats::Stats_DoubleValueStats* temp = _impl_.start_y_stats_;
  _impl_.start_y_stats_ = nullptr;
  return temp;
}
inline ::mozc::usage_stats::Stats_DoubleValueStats* Stats_TouchEventStats::_internal_mutable_start_y_stats() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.start_y_stats_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::mozc::usage_stats::Stats_DoubleValueStats>(GetArena());
    _impl_.start_y_stats_ = reinterpret_cast<::mozc::usage_stats::Stats_DoubleValueStats*>(p);
  }
  return _impl_.start_y_stats_;
}
inline ::mozc::usage_stats::Stats_DoubleValueStats* Stats_TouchEventStats::mutable_start_y_stats() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::mozc::usage_stats::Stats_DoubleValueStats* _msg = _internal_mutable_start_y_stats();
  // @@protoc_insertion_point(field_mutable:mozc.usage_stats.Stats.TouchEventStats.start_y_stats)
  return _msg;
}
inline void Stats_TouchEventStats::set_allocated_start_y_stats(::mozc::usage_stats::Stats_DoubleValueStats* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.start_y_stats_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.start_y_stats_ = reinterpret_cast<::mozc::usage_stats::Stats_DoubleValueStats*>(value);
  // @@protoc_insertion_point(field_set_allocated:mozc.usage_stats.Stats.TouchEventStats.start_y_stats)
}

// optional .mozc.usage_stats.Stats.DoubleValueStats direction_x_stats = 4;
inline bool Stats_TouchEventStats::has_direction_x_stats() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.direction_x_stats_ != nullptr);
  return value;
}
inline void Stats_TouchEventStats::clear_direction_x_stats() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.direction_x_stats_ != nullptr) _impl_.direction_x_stats_->Clear();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const ::mozc::usage_stats::Stats_DoubleValueStats& Stats_TouchEventStats::_internal_direction_x_stats() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::mozc::usage_stats::Stats_DoubleValueStats* p = _impl_.direction_x_stats_;
  return p != nullptr ? *p : reinterpret_cast<const ::mozc::usage_stats::Stats_DoubleValueStats&>(::mozc::usage_stats::_Stats_DoubleValueStats_default_instance_);
}
inline const ::mozc::usage_stats::Stats_DoubleValueStats& Stats_TouchEventStats::direction_x_stats() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mozc.usage_stats.Stats.TouchEventStats.direction_x_stats)
  return _internal_direction_x_stats();
}
inline void Stats_TouchEventStats::unsafe_arena_set_allocated_direction_x_stats(::mozc::usage_stats::Stats_DoubleValueStats* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.direction_x_stats_);
  }
  _impl_.direction_x_stats_ = reinterpret_cast<::mozc::usage_stats::Stats_DoubleValueStats*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mozc.usage_stats.Stats.TouchEventStats.direction_x_stats)
}
inline ::mozc::usage_stats::Stats_DoubleValueStats* Stats_TouchEventStats::release_direction_x_stats() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::mozc::usage_stats::Stats_DoubleValueStats* released = _impl_.direction_x_stats_;
  _impl_.direction_x_stats_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::mozc::usage_stats::Stats_DoubleValueStats* Stats_TouchEventStats::unsafe_arena_release_direction_x_stats() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mozc.usage_stats.Stats.TouchEventStats.direction_x_stats)

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::mozc::usage_stats::Stats_DoubleValueStats* temp = _impl_.direction_x_stats_;
  _impl_.direction_x_stats_ = nullptr;
  return temp;
}
inline ::mozc::usage_stats::Stats_DoubleValueStats* Stats_TouchEventStats::_internal_mutable_direction_x_stats() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.direction_x_stats_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::mozc::usage_stats::Stats_DoubleValueStats>(GetArena());
    _impl_.direction_x_stats_ = reinterpret_cast<::mozc::usage_stats::Stats_DoubleValueStats*>(p);
  }
  return _impl_.direction_x_stats_;
}
inline ::mozc::usage_stats::Stats_DoubleValueStats* Stats_TouchEventStats::mutable_direction_x_stats() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000004u;
  ::mozc::usage_stats::Stats_DoubleValueStats* _msg = _internal_mutable_direction_x_stats();
  // @@protoc_insertion_point(field_mutable:mozc.usage_stats.Stats.TouchEventStats.direction_x_stats)
  return _msg;
}
inline void Stats_TouchEventStats::set_allocated_direction_x_stats(::mozc::usage_stats::Stats_DoubleValueStats* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.direction_x_stats_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }

  _impl_.direction_x_stats_ = reinterpret_cast<::mozc::usage_stats::Stats_DoubleValueStats*>(value);
  // @@protoc_insertion_point(field_set_allocated:mozc.usage_stats.Stats.TouchEventStats.direction_x_stats)
}

// optional .mozc.usage_stats.Stats.DoubleValueStats direction_y_stats = 5;
inline bool Stats_TouchEventStats::has_direction_y_stats() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.direction_y_stats_ != nullptr);
  return value;
}
inline void Stats_TouchEventStats::clear_direction_y_stats() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.direction_y_stats_ != nullptr) _impl_.direction_y_stats_->Clear();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline const ::mozc::usage_stats::Stats_DoubleValueStats& Stats_TouchEventStats::_internal_direction_y_stats() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::mozc::usage_stats::Stats_DoubleValueStats* p = _impl_.direction_y_stats_;
  return p != nullptr ? *p : reinterpret_cast<const ::mozc::usage_stats::Stats_DoubleValueStats&>(::mozc::usage_stats::_Stats_DoubleValueStats_default_instance_);
}
inline const ::mozc::usage_stats::Stats_DoubleValueStats& Stats_TouchEventStats::direction_y_stats() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mozc.usage_stats.Stats.TouchEventStats.direction_y_stats)
  return _internal_direction_y_stats();
}
inline void Stats_TouchEventStats::unsafe_arena_set_allocated_direction_y_stats(::mozc::usage_stats::Stats_DoubleValueStats* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.direction_y_stats_);
  }
  _impl_.direction_y_stats_ = reinterpret_cast<::mozc::usage_stats::Stats_DoubleValueStats*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mozc.usage_stats.Stats.TouchEventStats.direction_y_stats)
}
inline ::mozc::usage_stats::Stats_DoubleValueStats* Stats_TouchEventStats::release_direction_y_stats() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000008u;
  ::mozc::usage_stats::Stats_DoubleValueStats* released = _impl_.direction_y_stats_;
  _impl_.direction_y_stats_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::mozc::usage_stats::Stats_DoubleValueStats* Stats_TouchEventStats::unsafe_arena_release_direction_y_stats() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mozc.usage_stats.Stats.TouchEventStats.direction_y_stats)

  _impl_._has_bits_[0] &= ~0x00000008u;
  ::mozc::usage_stats::Stats_DoubleValueStats* temp = _impl_.direction_y_stats_;
  _impl_.direction_y_stats_ = nullptr;
  return temp;
}
inline ::mozc::usage_stats::Stats_DoubleValueStats* Stats_TouchEventStats::_internal_mutable_direction_y_stats() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.direction_y_stats_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::mozc::usage_stats::Stats_DoubleValueStats>(GetArena());
    _impl_.direction_y_stats_ = reinterpret_cast<::mozc::usage_stats::Stats_DoubleValueStats*>(p);
  }
  return _impl_.direction_y_stats_;
}
inline ::mozc::usage_stats::Stats_DoubleValueStats* Stats_TouchEventStats::mutable_direction_y_stats() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000008u;
  ::mozc::usage_stats::Stats_DoubleValueStats* _msg = _internal_mutable_direction_y_stats();
  // @@protoc_insertion_point(field_mutable:mozc.usage_stats.Stats.TouchEventStats.direction_y_stats)
  return _msg;
}
inline void Stats_TouchEventStats::set_allocated_direction_y_stats(::mozc::usage_stats::Stats_DoubleValueStats* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.direction_y_stats_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }

  _impl_.direction_y_stats_ = reinterpret_cast<::mozc::usage_stats::Stats_DoubleValueStats*>(value);
  // @@protoc_insertion_point(field_set_allocated:mozc.usage_stats.Stats.TouchEventStats.direction_y_stats)
}

// optional .mozc.usage_stats.Stats.DoubleValueStats time_length_stats = 6;
inline bool Stats_TouchEventStats::has_time_length_stats() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.time_length_stats_ != nullptr);
  return value;
}
inline void Stats_TouchEventStats::clear_time_length_stats() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.time_length_stats_ != nullptr) _impl_.time_length_stats_->Clear();
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline const ::mozc::usage_stats::Stats_DoubleValueStats& Stats_TouchEventStats::_internal_time_length_stats() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::mozc::usage_stats::Stats_DoubleValueStats* p = _impl_.time_length_stats_;
  return p != nullptr ? *p : reinterpret_cast<const ::mozc::usage_stats::Stats_DoubleValueStats&>(::mozc::usage_stats::_Stats_DoubleValueStats_default_instance_);
}
inline const ::mozc::usage_stats::Stats_DoubleValueStats& Stats_TouchEventStats::time_length_stats() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mozc.usage_stats.Stats.TouchEventStats.time_length_stats)
  return _internal_time_length_stats();
}
inline void Stats_TouchEventStats::unsafe_arena_set_allocated_time_length_stats(::mozc::usage_stats::Stats_DoubleValueStats* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.time_length_stats_);
  }
  _impl_.time_length_stats_ = reinterpret_cast<::mozc::usage_stats::Stats_DoubleValueStats*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000010u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000010u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mozc.usage_stats.Stats.TouchEventStats.time_length_stats)
}
inline ::mozc::usage_stats::Stats_DoubleValueStats* Stats_TouchEventStats::release_time_length_stats() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000010u;
  ::mozc::usage_stats::Stats_DoubleValueStats* released = _impl_.time_length_stats_;
  _impl_.time_length_stats_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::mozc::usage_stats::Stats_DoubleValueStats* Stats_TouchEventStats::unsafe_arena_release_time_length_stats() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mozc.usage_stats.Stats.TouchEventStats.time_length_stats)

  _impl_._has_bits_[0] &= ~0x00000010u;
  ::mozc::usage_stats::Stats_DoubleValueStats* temp = _impl_.time_length_stats_;
  _impl_.time_length_stats_ = nullptr;
  return temp;
}
inline ::mozc::usage_stats::Stats_DoubleValueStats* Stats_TouchEventStats::_internal_mutable_time_length_stats() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.time_length_stats_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::mozc::usage_stats::Stats_DoubleValueStats>(GetArena());
    _impl_.time_length_stats_ = reinterpret_cast<::mozc::usage_stats::Stats_DoubleValueStats*>(p);
  }
  return _impl_.time_length_stats_;
}
inline ::mozc::usage_stats::Stats_DoubleValueStats* Stats_TouchEventStats::mutable_time_length_stats() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000010u;
  ::mozc::usage_stats::Stats_DoubleValueStats* _msg = _internal_mutable_time_length_stats();
  // @@protoc_insertion_point(field_mutable:mozc.usage_stats.Stats.TouchEventStats.time_length_stats)
  return _msg;
}
inline void Stats_TouchEventStats::set_allocated_time_length_stats(::mozc::usage_stats::Stats_DoubleValueStats* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.time_length_stats_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000010u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000010u;
  }

  _impl_.time_length_stats_ = reinterpret_cast<::mozc::usage_stats::Stats_DoubleValueStats*>(value);
  // @@protoc_insertion_point(field_set_allocated:mozc.usage_stats.Stats.TouchEventStats.time_length_stats)
}

// -------------------------------------------------------------------

// Stats_VirtualKeyboardStats

// optional string keyboard_name = 1;
inline bool Stats_VirtualKeyboardStats::has_keyboard_name() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void Stats_VirtualKeyboardStats::clear_keyboard_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.keyboard_name_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Stats_VirtualKeyboardStats::keyboard_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mozc.usage_stats.Stats.VirtualKeyboardStats.keyboard_name)
  return _internal_keyboard_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Stats_VirtualKeyboardStats::set_keyboard_name(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.keyboard_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:mozc.usage_stats.Stats.VirtualKeyboardStats.keyboard_name)
}
inline std::string* Stats_VirtualKeyboardStats::mutable_keyboard_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_keyboard_name();
  // @@protoc_insertion_point(field_mutable:mozc.usage_stats.Stats.VirtualKeyboardStats.keyboard_name)
  return _s;
}
inline const std::string& Stats_VirtualKeyboardStats::_internal_keyboard_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.keyboard_name_.Get();
}
inline void Stats_VirtualKeyboardStats::_internal_set_keyboard_name(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.keyboard_name_.Set(value, GetArena());
}
inline std::string* Stats_VirtualKeyboardStats::_internal_mutable_keyboard_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.keyboard_name_.Mutable( GetArena());
}
inline std::string* Stats_VirtualKeyboardStats::release_keyboard_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mozc.usage_stats.Stats.VirtualKeyboardStats.keyboard_name)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.keyboard_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.keyboard_name_.Set("", GetArena());
  }
  return released;
}
inline void Stats_VirtualKeyboardStats::set_allocated_keyboard_name(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.keyboard_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.keyboard_name_.IsDefault()) {
    _impl_.keyboard_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:mozc.usage_stats.Stats.VirtualKeyboardStats.keyboard_name)
}

// repeated .mozc.usage_stats.Stats.TouchEventStats touch_event_stats = 2;
inline int Stats_VirtualKeyboardStats::_internal_touch_event_stats_size() const {
  return _internal_touch_event_stats().size();
}
inline int Stats_VirtualKeyboardStats::touch_event_stats_size() const {
  return _internal_touch_event_stats_size();
}
inline void Stats_VirtualKeyboardStats::clear_touch_event_stats() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.touch_event_stats_.Clear();
}
inline ::mozc::usage_stats::Stats_TouchEventStats* Stats_VirtualKeyboardStats::mutable_touch_event_stats(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:mozc.usage_stats.Stats.VirtualKeyboardStats.touch_event_stats)
  return _internal_mutable_touch_event_stats()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::mozc::usage_stats::Stats_TouchEventStats>* Stats_VirtualKeyboardStats::mutable_touch_event_stats()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:mozc.usage_stats.Stats.VirtualKeyboardStats.touch_event_stats)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_touch_event_stats();
}
inline const ::mozc::usage_stats::Stats_TouchEventStats& Stats_VirtualKeyboardStats::touch_event_stats(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mozc.usage_stats.Stats.VirtualKeyboardStats.touch_event_stats)
  return _internal_touch_event_stats().Get(index);
}
inline ::mozc::usage_stats::Stats_TouchEventStats* Stats_VirtualKeyboardStats::add_touch_event_stats() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::mozc::usage_stats::Stats_TouchEventStats* _add = _internal_mutable_touch_event_stats()->Add();
  // @@protoc_insertion_point(field_add:mozc.usage_stats.Stats.VirtualKeyboardStats.touch_event_stats)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::mozc::usage_stats::Stats_TouchEventStats>& Stats_VirtualKeyboardStats::touch_event_stats() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:mozc.usage_stats.Stats.VirtualKeyboardStats.touch_event_stats)
  return _internal_touch_event_stats();
}
inline const ::google::protobuf::RepeatedPtrField<::mozc::usage_stats::Stats_TouchEventStats>&
Stats_VirtualKeyboardStats::_internal_touch_event_stats() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.touch_event_stats_;
}
inline ::google::protobuf::RepeatedPtrField<::mozc::usage_stats::Stats_TouchEventStats>*
Stats_VirtualKeyboardStats::_internal_mutable_touch_event_stats() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.touch_event_stats_;
}

// -------------------------------------------------------------------

// Stats

// required string name = 1;
inline bool Stats::has_name() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void Stats::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Stats::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mozc.usage_stats.Stats.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Stats::set_name(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:mozc.usage_stats.Stats.name)
}
inline std::string* Stats::mutable_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:mozc.usage_stats.Stats.name)
  return _s;
}
inline const std::string& Stats::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void Stats::_internal_set_name(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.name_.Set(value, GetArena());
}
inline std::string* Stats::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.name_.Mutable( GetArena());
}
inline std::string* Stats::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mozc.usage_stats.Stats.name)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.name_.Set("", GetArena());
  }
  return released;
}
inline void Stats::set_allocated_name(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:mozc.usage_stats.Stats.name)
}

// required .mozc.usage_stats.Stats.Type type = 2;
inline bool Stats::has_type() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void Stats::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::mozc::usage_stats::Stats_Type Stats::type() const {
  // @@protoc_insertion_point(field_get:mozc.usage_stats.Stats.type)
  return _internal_type();
}
inline void Stats::set_type(::mozc::usage_stats::Stats_Type value) {
  _internal_set_type(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:mozc.usage_stats.Stats.type)
}
inline ::mozc::usage_stats::Stats_Type Stats::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::mozc::usage_stats::Stats_Type>(_impl_.type_);
}
inline void Stats::_internal_set_type(::mozc::usage_stats::Stats_Type value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  assert(::mozc::usage_stats::Stats_Type_IsValid(value));
  _impl_.type_ = value;
}

// optional uint32 count = 3;
inline bool Stats::has_count() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void Stats::clear_count() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.count_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::uint32_t Stats::count() const {
  // @@protoc_insertion_point(field_get:mozc.usage_stats.Stats.count)
  return _internal_count();
}
inline void Stats::set_count(::uint32_t value) {
  _internal_set_count(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:mozc.usage_stats.Stats.count)
}
inline ::uint32_t Stats::_internal_count() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.count_;
}
inline void Stats::_internal_set_count(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.count_ = value;
}

// optional uint64 total_time = 10;
inline bool Stats::has_total_time() const {
  bool value = (_impl_._has_bits_[0] & 0x00000200u) != 0;
  return value;
}
inline void Stats::clear_total_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.total_time_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000200u;
}
inline ::uint64_t Stats::total_time() const {
  // @@protoc_insertion_point(field_get:mozc.usage_stats.Stats.total_time)
  return _internal_total_time();
}
inline void Stats::set_total_time(::uint64_t value) {
  _internal_set_total_time(value);
  _impl_._has_bits_[0] |= 0x00000200u;
  // @@protoc_insertion_point(field_set:mozc.usage_stats.Stats.total_time)
}
inline ::uint64_t Stats::_internal_total_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.total_time_;
}
inline void Stats::_internal_set_total_time(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.total_time_ = value;
}

// optional uint32 num_timings = 4;
inline bool Stats::has_num_timings() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void Stats::clear_num_timings() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num_timings_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::uint32_t Stats::num_timings() const {
  // @@protoc_insertion_point(field_get:mozc.usage_stats.Stats.num_timings)
  return _internal_num_timings();
}
inline void Stats::set_num_timings(::uint32_t value) {
  _internal_set_num_timings(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:mozc.usage_stats.Stats.num_timings)
}
inline ::uint32_t Stats::_internal_num_timings() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.num_timings_;
}
inline void Stats::_internal_set_num_timings(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num_timings_ = value;
}

// optional uint32 avg_time = 5;
inline bool Stats::has_avg_time() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline void Stats::clear_avg_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.avg_time_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline ::uint32_t Stats::avg_time() const {
  // @@protoc_insertion_point(field_get:mozc.usage_stats.Stats.avg_time)
  return _internal_avg_time();
}
inline void Stats::set_avg_time(::uint32_t value) {
  _internal_set_avg_time(value);
  _impl_._has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_set:mozc.usage_stats.Stats.avg_time)
}
inline ::uint32_t Stats::_internal_avg_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.avg_time_;
}
inline void Stats::_internal_set_avg_time(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.avg_time_ = value;
}

// optional uint32 min_time = 6;
inline bool Stats::has_min_time() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline void Stats::clear_min_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.min_time_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline ::uint32_t Stats::min_time() const {
  // @@protoc_insertion_point(field_get:mozc.usage_stats.Stats.min_time)
  return _internal_min_time();
}
inline void Stats::set_min_time(::uint32_t value) {
  _internal_set_min_time(value);
  _impl_._has_bits_[0] |= 0x00000020u;
  // @@protoc_insertion_point(field_set:mozc.usage_stats.Stats.min_time)
}
inline ::uint32_t Stats::_internal_min_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.min_time_;
}
inline void Stats::_internal_set_min_time(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.min_time_ = value;
}

// optional uint32 max_time = 7;
inline bool Stats::has_max_time() const {
  bool value = (_impl_._has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline void Stats::clear_max_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_time_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline ::uint32_t Stats::max_time() const {
  // @@protoc_insertion_point(field_get:mozc.usage_stats.Stats.max_time)
  return _internal_max_time();
}
inline void Stats::set_max_time(::uint32_t value) {
  _internal_set_max_time(value);
  _impl_._has_bits_[0] |= 0x00000040u;
  // @@protoc_insertion_point(field_set:mozc.usage_stats.Stats.max_time)
}
inline ::uint32_t Stats::_internal_max_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.max_time_;
}
inline void Stats::_internal_set_max_time(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_time_ = value;
}

// optional int32 int_value = 8;
inline bool Stats::has_int_value() const {
  bool value = (_impl_._has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline void Stats::clear_int_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.int_value_ = 0;
  _impl_._has_bits_[0] &= ~0x00000080u;
}
inline ::int32_t Stats::int_value() const {
  // @@protoc_insertion_point(field_get:mozc.usage_stats.Stats.int_value)
  return _internal_int_value();
}
inline void Stats::set_int_value(::int32_t value) {
  _internal_set_int_value(value);
  _impl_._has_bits_[0] |= 0x00000080u;
  // @@protoc_insertion_point(field_set:mozc.usage_stats.Stats.int_value)
}
inline ::int32_t Stats::_internal_int_value() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.int_value_;
}
inline void Stats::_internal_set_int_value(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.int_value_ = value;
}

// optional bool boolean_value = 9;
inline bool Stats::has_boolean_value() const {
  bool value = (_impl_._has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline void Stats::clear_boolean_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.boolean_value_ = false;
  _impl_._has_bits_[0] &= ~0x00000100u;
}
inline bool Stats::boolean_value() const {
  // @@protoc_insertion_point(field_get:mozc.usage_stats.Stats.boolean_value)
  return _internal_boolean_value();
}
inline void Stats::set_boolean_value(bool value) {
  _internal_set_boolean_value(value);
  _impl_._has_bits_[0] |= 0x00000100u;
  // @@protoc_insertion_point(field_set:mozc.usage_stats.Stats.boolean_value)
}
inline bool Stats::_internal_boolean_value() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.boolean_value_;
}
inline void Stats::_internal_set_boolean_value(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.boolean_value_ = value;
}

// repeated .mozc.usage_stats.Stats.VirtualKeyboardStats virtual_keyboard_stats = 11;
inline int Stats::_internal_virtual_keyboard_stats_size() const {
  return _internal_virtual_keyboard_stats().size();
}
inline int Stats::virtual_keyboard_stats_size() const {
  return _internal_virtual_keyboard_stats_size();
}
inline void Stats::clear_virtual_keyboard_stats() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.virtual_keyboard_stats_.Clear();
}
inline ::mozc::usage_stats::Stats_VirtualKeyboardStats* Stats::mutable_virtual_keyboard_stats(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:mozc.usage_stats.Stats.virtual_keyboard_stats)
  return _internal_mutable_virtual_keyboard_stats()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::mozc::usage_stats::Stats_VirtualKeyboardStats>* Stats::mutable_virtual_keyboard_stats()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:mozc.usage_stats.Stats.virtual_keyboard_stats)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_virtual_keyboard_stats();
}
inline const ::mozc::usage_stats::Stats_VirtualKeyboardStats& Stats::virtual_keyboard_stats(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mozc.usage_stats.Stats.virtual_keyboard_stats)
  return _internal_virtual_keyboard_stats().Get(index);
}
inline ::mozc::usage_stats::Stats_VirtualKeyboardStats* Stats::add_virtual_keyboard_stats() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::mozc::usage_stats::Stats_VirtualKeyboardStats* _add = _internal_mutable_virtual_keyboard_stats()->Add();
  // @@protoc_insertion_point(field_add:mozc.usage_stats.Stats.virtual_keyboard_stats)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::mozc::usage_stats::Stats_VirtualKeyboardStats>& Stats::virtual_keyboard_stats() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:mozc.usage_stats.Stats.virtual_keyboard_stats)
  return _internal_virtual_keyboard_stats();
}
inline const ::google::protobuf::RepeatedPtrField<::mozc::usage_stats::Stats_VirtualKeyboardStats>&
Stats::_internal_virtual_keyboard_stats() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.virtual_keyboard_stats_;
}
inline ::google::protobuf::RepeatedPtrField<::mozc::usage_stats::Stats_VirtualKeyboardStats>*
Stats::_internal_mutable_virtual_keyboard_stats() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.virtual_keyboard_stats_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace usage_stats
}  // namespace mozc


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::mozc::usage_stats::Stats_Type> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::mozc::usage_stats::Stats_Type>() {
  return ::mozc::usage_stats::Stats_Type_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // usage_5fstats_2fusage_5fstats_2eproto_2epb_2eh
