// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protocol/engine_builder.proto
// Protobuf C++ Version: 5.29.1

#ifndef protocol_2fengine_5fbuilder_2eproto_2epb_2eh
#define protocol_2fengine_5fbuilder_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_protocol_2fengine_5fbuilder_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_protocol_2fengine_5fbuilder_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_protocol_2fengine_5fbuilder_2eproto;
namespace mozc {
class EngineReloadRequest;
struct EngineReloadRequestDefaultTypeInternal;
extern EngineReloadRequestDefaultTypeInternal _EngineReloadRequest_default_instance_;
class EngineReloadResponse;
struct EngineReloadResponseDefaultTypeInternal;
extern EngineReloadResponseDefaultTypeInternal _EngineReloadResponse_default_instance_;
}  // namespace mozc
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace mozc {
enum EngineReloadRequest_EngineType : int {
  EngineReloadRequest_EngineType_DESKTOP = 0,
  EngineReloadRequest_EngineType_MOBILE = 1,
};

bool EngineReloadRequest_EngineType_IsValid(int value);
extern const uint32_t EngineReloadRequest_EngineType_internal_data_[];
constexpr EngineReloadRequest_EngineType EngineReloadRequest_EngineType_EngineType_MIN = static_cast<EngineReloadRequest_EngineType>(0);
constexpr EngineReloadRequest_EngineType EngineReloadRequest_EngineType_EngineType_MAX = static_cast<EngineReloadRequest_EngineType>(1);
constexpr int EngineReloadRequest_EngineType_EngineType_ARRAYSIZE = 1 + 1;
const ::google::protobuf::EnumDescriptor*
EngineReloadRequest_EngineType_descriptor();
template <typename T>
const std::string& EngineReloadRequest_EngineType_Name(T value) {
  static_assert(std::is_same<T, EngineReloadRequest_EngineType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to EngineType_Name().");
  return EngineReloadRequest_EngineType_Name(static_cast<EngineReloadRequest_EngineType>(value));
}
template <>
inline const std::string& EngineReloadRequest_EngineType_Name(EngineReloadRequest_EngineType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<EngineReloadRequest_EngineType_descriptor,
                                                 0, 1>(
      static_cast<int>(value));
}
inline bool EngineReloadRequest_EngineType_Parse(absl::string_view name, EngineReloadRequest_EngineType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<EngineReloadRequest_EngineType>(
      EngineReloadRequest_EngineType_descriptor(), name, value);
}
enum EngineReloadResponse_Status : int {
  EngineReloadResponse_Status_ACCEPTED = 0,
  EngineReloadResponse_Status_RELOAD_READY = 1,
  EngineReloadResponse_Status_RELOADED = 2,
  EngineReloadResponse_Status_ALREADY_RUNNING = 3,
  EngineReloadResponse_Status_ENGINE_VERSION_MISMATCH = 4,
  EngineReloadResponse_Status_DATA_MISSING = 5,
  EngineReloadResponse_Status_DATA_BROKEN = 6,
  EngineReloadResponse_Status_MMAP_FAILURE = 7,
  EngineReloadResponse_Status_UNKNOWN_ERROR = 9,
};

bool EngineReloadResponse_Status_IsValid(int value);
extern const uint32_t EngineReloadResponse_Status_internal_data_[];
constexpr EngineReloadResponse_Status EngineReloadResponse_Status_Status_MIN = static_cast<EngineReloadResponse_Status>(0);
constexpr EngineReloadResponse_Status EngineReloadResponse_Status_Status_MAX = static_cast<EngineReloadResponse_Status>(9);
constexpr int EngineReloadResponse_Status_Status_ARRAYSIZE = 9 + 1;
const ::google::protobuf::EnumDescriptor*
EngineReloadResponse_Status_descriptor();
template <typename T>
const std::string& EngineReloadResponse_Status_Name(T value) {
  static_assert(std::is_same<T, EngineReloadResponse_Status>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to Status_Name().");
  return EngineReloadResponse_Status_Name(static_cast<EngineReloadResponse_Status>(value));
}
template <>
inline const std::string& EngineReloadResponse_Status_Name(EngineReloadResponse_Status value) {
  return ::google::protobuf::internal::NameOfDenseEnum<EngineReloadResponse_Status_descriptor,
                                                 0, 9>(
      static_cast<int>(value));
}
inline bool EngineReloadResponse_Status_Parse(absl::string_view name, EngineReloadResponse_Status* value) {
  return ::google::protobuf::internal::ParseNamedEnum<EngineReloadResponse_Status>(
      EngineReloadResponse_Status_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class EngineReloadRequest final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:mozc.EngineReloadRequest) */ {
 public:
  inline EngineReloadRequest() : EngineReloadRequest(nullptr) {}
  ~EngineReloadRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(EngineReloadRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(EngineReloadRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR EngineReloadRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline EngineReloadRequest(const EngineReloadRequest& from) : EngineReloadRequest(nullptr, from) {}
  inline EngineReloadRequest(EngineReloadRequest&& from) noexcept
      : EngineReloadRequest(nullptr, std::move(from)) {}
  inline EngineReloadRequest& operator=(const EngineReloadRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline EngineReloadRequest& operator=(EngineReloadRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EngineReloadRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const EngineReloadRequest* internal_default_instance() {
    return reinterpret_cast<const EngineReloadRequest*>(
        &_EngineReloadRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(EngineReloadRequest& a, EngineReloadRequest& b) { a.Swap(&b); }
  inline void Swap(EngineReloadRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EngineReloadRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  EngineReloadRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<EngineReloadRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const EngineReloadRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const EngineReloadRequest& from) { EngineReloadRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(EngineReloadRequest* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "mozc.EngineReloadRequest"; }

 protected:
  explicit EngineReloadRequest(::google::protobuf::Arena* arena);
  EngineReloadRequest(::google::protobuf::Arena* arena, const EngineReloadRequest& from);
  EngineReloadRequest(::google::protobuf::Arena* arena, EngineReloadRequest&& from) noexcept
      : EngineReloadRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using EngineType = EngineReloadRequest_EngineType;
  static constexpr EngineType DESKTOP = EngineReloadRequest_EngineType_DESKTOP;
  static constexpr EngineType MOBILE = EngineReloadRequest_EngineType_MOBILE;
  static inline bool EngineType_IsValid(int value) {
    return EngineReloadRequest_EngineType_IsValid(value);
  }
  static constexpr EngineType EngineType_MIN = EngineReloadRequest_EngineType_EngineType_MIN;
  static constexpr EngineType EngineType_MAX = EngineReloadRequest_EngineType_EngineType_MAX;
  static constexpr int EngineType_ARRAYSIZE = EngineReloadRequest_EngineType_EngineType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* EngineType_descriptor() {
    return EngineReloadRequest_EngineType_descriptor();
  }
  template <typename T>
  static inline const std::string& EngineType_Name(T value) {
    return EngineReloadRequest_EngineType_Name(value);
  }
  static inline bool EngineType_Parse(absl::string_view name, EngineType* value) {
    return EngineReloadRequest_EngineType_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kFilePathFieldNumber = 2,
    kMagicNumberFieldNumber = 4,
    kEngineTypeFieldNumber = 1,
    kPriorityFieldNumber = 5,
  };
  // required string file_path = 2;
  bool has_file_path() const;
  void clear_file_path() ;
  const std::string& file_path() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_file_path(Arg_&& arg, Args_... args);
  std::string* mutable_file_path();
  PROTOBUF_NODISCARD std::string* release_file_path();
  void set_allocated_file_path(std::string* value);

  private:
  const std::string& _internal_file_path() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_file_path(
      const std::string& value);
  std::string* _internal_mutable_file_path();

  public:
  // optional string magic_number = 4;
  bool has_magic_number() const;
  void clear_magic_number() ;
  const std::string& magic_number() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_magic_number(Arg_&& arg, Args_... args);
  std::string* mutable_magic_number();
  PROTOBUF_NODISCARD std::string* release_magic_number();
  void set_allocated_magic_number(std::string* value);

  private:
  const std::string& _internal_magic_number() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_magic_number(
      const std::string& value);
  std::string* _internal_mutable_magic_number();

  public:
  // required .mozc.EngineReloadRequest.EngineType engine_type = 1;
  bool has_engine_type() const;
  void clear_engine_type() ;
  ::mozc::EngineReloadRequest_EngineType engine_type() const;
  void set_engine_type(::mozc::EngineReloadRequest_EngineType value);

  private:
  ::mozc::EngineReloadRequest_EngineType _internal_engine_type() const;
  void _internal_set_engine_type(::mozc::EngineReloadRequest_EngineType value);

  public:
  // optional int32 priority = 5;
  bool has_priority() const;
  void clear_priority() ;
  ::int32_t priority() const;
  void set_priority(::int32_t value);

  private:
  ::int32_t _internal_priority() const;
  void _internal_set_priority(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:mozc.EngineReloadRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 4, 1,
      54, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const EngineReloadRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr file_path_;
    ::google::protobuf::internal::ArenaStringPtr magic_number_;
    int engine_type_;
    ::int32_t priority_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_protocol_2fengine_5fbuilder_2eproto;
};
// -------------------------------------------------------------------

class EngineReloadResponse final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:mozc.EngineReloadResponse) */ {
 public:
  inline EngineReloadResponse() : EngineReloadResponse(nullptr) {}
  ~EngineReloadResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(EngineReloadResponse* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(EngineReloadResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR EngineReloadResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline EngineReloadResponse(const EngineReloadResponse& from) : EngineReloadResponse(nullptr, from) {}
  inline EngineReloadResponse(EngineReloadResponse&& from) noexcept
      : EngineReloadResponse(nullptr, std::move(from)) {}
  inline EngineReloadResponse& operator=(const EngineReloadResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline EngineReloadResponse& operator=(EngineReloadResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EngineReloadResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const EngineReloadResponse* internal_default_instance() {
    return reinterpret_cast<const EngineReloadResponse*>(
        &_EngineReloadResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(EngineReloadResponse& a, EngineReloadResponse& b) { a.Swap(&b); }
  inline void Swap(EngineReloadResponse* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EngineReloadResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  EngineReloadResponse* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<EngineReloadResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const EngineReloadResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const EngineReloadResponse& from) { EngineReloadResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(EngineReloadResponse* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "mozc.EngineReloadResponse"; }

 protected:
  explicit EngineReloadResponse(::google::protobuf::Arena* arena);
  EngineReloadResponse(::google::protobuf::Arena* arena, const EngineReloadResponse& from);
  EngineReloadResponse(::google::protobuf::Arena* arena, EngineReloadResponse&& from) noexcept
      : EngineReloadResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Status = EngineReloadResponse_Status;
  static constexpr Status ACCEPTED = EngineReloadResponse_Status_ACCEPTED;
  static constexpr Status RELOAD_READY = EngineReloadResponse_Status_RELOAD_READY;
  static constexpr Status RELOADED = EngineReloadResponse_Status_RELOADED;
  static constexpr Status ALREADY_RUNNING = EngineReloadResponse_Status_ALREADY_RUNNING;
  static constexpr Status ENGINE_VERSION_MISMATCH = EngineReloadResponse_Status_ENGINE_VERSION_MISMATCH;
  static constexpr Status DATA_MISSING = EngineReloadResponse_Status_DATA_MISSING;
  static constexpr Status DATA_BROKEN = EngineReloadResponse_Status_DATA_BROKEN;
  static constexpr Status MMAP_FAILURE = EngineReloadResponse_Status_MMAP_FAILURE;
  static constexpr Status UNKNOWN_ERROR = EngineReloadResponse_Status_UNKNOWN_ERROR;
  static inline bool Status_IsValid(int value) {
    return EngineReloadResponse_Status_IsValid(value);
  }
  static constexpr Status Status_MIN = EngineReloadResponse_Status_Status_MIN;
  static constexpr Status Status_MAX = EngineReloadResponse_Status_Status_MAX;
  static constexpr int Status_ARRAYSIZE = EngineReloadResponse_Status_Status_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* Status_descriptor() {
    return EngineReloadResponse_Status_descriptor();
  }
  template <typename T>
  static inline const std::string& Status_Name(T value) {
    return EngineReloadResponse_Status_Name(value);
  }
  static inline bool Status_Parse(absl::string_view name, Status* value) {
    return EngineReloadResponse_Status_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kRequestFieldNumber = 2,
    kStatusFieldNumber = 1,
  };
  // optional .mozc.EngineReloadRequest request = 2;
  bool has_request() const;
  void clear_request() ;
  const ::mozc::EngineReloadRequest& request() const;
  PROTOBUF_NODISCARD ::mozc::EngineReloadRequest* release_request();
  ::mozc::EngineReloadRequest* mutable_request();
  void set_allocated_request(::mozc::EngineReloadRequest* value);
  void unsafe_arena_set_allocated_request(::mozc::EngineReloadRequest* value);
  ::mozc::EngineReloadRequest* unsafe_arena_release_request();

  private:
  const ::mozc::EngineReloadRequest& _internal_request() const;
  ::mozc::EngineReloadRequest* _internal_mutable_request();

  public:
  // required .mozc.EngineReloadResponse.Status status = 1;
  bool has_status() const;
  void clear_status() ;
  ::mozc::EngineReloadResponse_Status status() const;
  void set_status(::mozc::EngineReloadResponse_Status value);

  private:
  ::mozc::EngineReloadResponse_Status _internal_status() const;
  void _internal_set_status(::mozc::EngineReloadResponse_Status value);

  public:
  // @@protoc_insertion_point(class_scope:mozc.EngineReloadResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 2,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const EngineReloadResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::mozc::EngineReloadRequest* request_;
    int status_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_protocol_2fengine_5fbuilder_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// EngineReloadRequest

// required .mozc.EngineReloadRequest.EngineType engine_type = 1;
inline bool EngineReloadRequest::has_engine_type() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void EngineReloadRequest::clear_engine_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.engine_type_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::mozc::EngineReloadRequest_EngineType EngineReloadRequest::engine_type() const {
  // @@protoc_insertion_point(field_get:mozc.EngineReloadRequest.engine_type)
  return _internal_engine_type();
}
inline void EngineReloadRequest::set_engine_type(::mozc::EngineReloadRequest_EngineType value) {
  _internal_set_engine_type(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:mozc.EngineReloadRequest.engine_type)
}
inline ::mozc::EngineReloadRequest_EngineType EngineReloadRequest::_internal_engine_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::mozc::EngineReloadRequest_EngineType>(_impl_.engine_type_);
}
inline void EngineReloadRequest::_internal_set_engine_type(::mozc::EngineReloadRequest_EngineType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  assert(::mozc::EngineReloadRequest_EngineType_IsValid(value));
  _impl_.engine_type_ = value;
}

// required string file_path = 2;
inline bool EngineReloadRequest::has_file_path() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void EngineReloadRequest::clear_file_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.file_path_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& EngineReloadRequest::file_path() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mozc.EngineReloadRequest.file_path)
  return _internal_file_path();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void EngineReloadRequest::set_file_path(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.file_path_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:mozc.EngineReloadRequest.file_path)
}
inline std::string* EngineReloadRequest::mutable_file_path() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_file_path();
  // @@protoc_insertion_point(field_mutable:mozc.EngineReloadRequest.file_path)
  return _s;
}
inline const std::string& EngineReloadRequest::_internal_file_path() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.file_path_.Get();
}
inline void EngineReloadRequest::_internal_set_file_path(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.file_path_.Set(value, GetArena());
}
inline std::string* EngineReloadRequest::_internal_mutable_file_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.file_path_.Mutable( GetArena());
}
inline std::string* EngineReloadRequest::release_file_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mozc.EngineReloadRequest.file_path)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.file_path_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.file_path_.Set("", GetArena());
  }
  return released;
}
inline void EngineReloadRequest::set_allocated_file_path(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.file_path_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.file_path_.IsDefault()) {
    _impl_.file_path_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:mozc.EngineReloadRequest.file_path)
}

// optional string magic_number = 4;
inline bool EngineReloadRequest::has_magic_number() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void EngineReloadRequest::clear_magic_number() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.magic_number_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& EngineReloadRequest::magic_number() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mozc.EngineReloadRequest.magic_number)
  return _internal_magic_number();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void EngineReloadRequest::set_magic_number(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.magic_number_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:mozc.EngineReloadRequest.magic_number)
}
inline std::string* EngineReloadRequest::mutable_magic_number() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_magic_number();
  // @@protoc_insertion_point(field_mutable:mozc.EngineReloadRequest.magic_number)
  return _s;
}
inline const std::string& EngineReloadRequest::_internal_magic_number() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.magic_number_.Get();
}
inline void EngineReloadRequest::_internal_set_magic_number(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.magic_number_.Set(value, GetArena());
}
inline std::string* EngineReloadRequest::_internal_mutable_magic_number() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.magic_number_.Mutable( GetArena());
}
inline std::string* EngineReloadRequest::release_magic_number() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mozc.EngineReloadRequest.magic_number)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.magic_number_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.magic_number_.Set("", GetArena());
  }
  return released;
}
inline void EngineReloadRequest::set_allocated_magic_number(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.magic_number_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.magic_number_.IsDefault()) {
    _impl_.magic_number_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:mozc.EngineReloadRequest.magic_number)
}

// optional int32 priority = 5;
inline bool EngineReloadRequest::has_priority() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void EngineReloadRequest::clear_priority() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.priority_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::int32_t EngineReloadRequest::priority() const {
  // @@protoc_insertion_point(field_get:mozc.EngineReloadRequest.priority)
  return _internal_priority();
}
inline void EngineReloadRequest::set_priority(::int32_t value) {
  _internal_set_priority(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:mozc.EngineReloadRequest.priority)
}
inline ::int32_t EngineReloadRequest::_internal_priority() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.priority_;
}
inline void EngineReloadRequest::_internal_set_priority(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.priority_ = value;
}

// -------------------------------------------------------------------

// EngineReloadResponse

// required .mozc.EngineReloadResponse.Status status = 1;
inline bool EngineReloadResponse::has_status() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void EngineReloadResponse::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::mozc::EngineReloadResponse_Status EngineReloadResponse::status() const {
  // @@protoc_insertion_point(field_get:mozc.EngineReloadResponse.status)
  return _internal_status();
}
inline void EngineReloadResponse::set_status(::mozc::EngineReloadResponse_Status value) {
  _internal_set_status(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:mozc.EngineReloadResponse.status)
}
inline ::mozc::EngineReloadResponse_Status EngineReloadResponse::_internal_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::mozc::EngineReloadResponse_Status>(_impl_.status_);
}
inline void EngineReloadResponse::_internal_set_status(::mozc::EngineReloadResponse_Status value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  assert(::mozc::EngineReloadResponse_Status_IsValid(value));
  _impl_.status_ = value;
}

// optional .mozc.EngineReloadRequest request = 2;
inline bool EngineReloadResponse::has_request() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.request_ != nullptr);
  return value;
}
inline void EngineReloadResponse::clear_request() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.request_ != nullptr) _impl_.request_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::mozc::EngineReloadRequest& EngineReloadResponse::_internal_request() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::mozc::EngineReloadRequest* p = _impl_.request_;
  return p != nullptr ? *p : reinterpret_cast<const ::mozc::EngineReloadRequest&>(::mozc::_EngineReloadRequest_default_instance_);
}
inline const ::mozc::EngineReloadRequest& EngineReloadResponse::request() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mozc.EngineReloadResponse.request)
  return _internal_request();
}
inline void EngineReloadResponse::unsafe_arena_set_allocated_request(::mozc::EngineReloadRequest* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.request_);
  }
  _impl_.request_ = reinterpret_cast<::mozc::EngineReloadRequest*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mozc.EngineReloadResponse.request)
}
inline ::mozc::EngineReloadRequest* EngineReloadResponse::release_request() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::mozc::EngineReloadRequest* released = _impl_.request_;
  _impl_.request_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::mozc::EngineReloadRequest* EngineReloadResponse::unsafe_arena_release_request() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mozc.EngineReloadResponse.request)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::mozc::EngineReloadRequest* temp = _impl_.request_;
  _impl_.request_ = nullptr;
  return temp;
}
inline ::mozc::EngineReloadRequest* EngineReloadResponse::_internal_mutable_request() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.request_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::mozc::EngineReloadRequest>(GetArena());
    _impl_.request_ = reinterpret_cast<::mozc::EngineReloadRequest*>(p);
  }
  return _impl_.request_;
}
inline ::mozc::EngineReloadRequest* EngineReloadResponse::mutable_request() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::mozc::EngineReloadRequest* _msg = _internal_mutable_request();
  // @@protoc_insertion_point(field_mutable:mozc.EngineReloadResponse.request)
  return _msg;
}
inline void EngineReloadResponse::set_allocated_request(::mozc::EngineReloadRequest* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.request_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.request_ = reinterpret_cast<::mozc::EngineReloadRequest*>(value);
  // @@protoc_insertion_point(field_set_allocated:mozc.EngineReloadResponse.request)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace mozc


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::mozc::EngineReloadRequest_EngineType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::mozc::EngineReloadRequest_EngineType>() {
  return ::mozc::EngineReloadRequest_EngineType_descriptor();
}
template <>
struct is_proto_enum<::mozc::EngineReloadResponse_Status> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::mozc::EngineReloadResponse_Status>() {
  return ::mozc::EngineReloadResponse_Status_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // protocol_2fengine_5fbuilder_2eproto_2epb_2eh
